import json
import os

file_path = r'c:\Users\eduar\OneDrive\Desktop\Antigravity\doughlabpro\public\locales\en\styles.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

new_keys = {
    # Focaccia Genovese
    "focaccia_intro": "Eaten plain or with simple toppings, often as a snack or accompaniment to meals and drinks.",
    "focaccia_history": "Focaccia Genovese (Fügassa in Ligurian dialect) is the ancestor of modern flatbreads, rooted in the maritime history of Genoa. Originally eaten by sailors and dockworkers for stamina, it was historically baked in communal ovens. The addition of a 'Salami' (brine) of water, salt, and oil in the holes was a clever way to keep the bread moist and savory during long voyages.",
    "focaccia_sig_1": "The culinary heartbeat of Genoa and the Ligurian coast",
    "focaccia_sig_2": "One of the few savory breads traditionally eaten dipped in breakfast coffee (cappuccino)",
    "focaccia_sig_3": "Protected as a traditional agri-food product (PAT) in Italy",
    "focaccia_sig_4": "Symbol of Ligurian hospitality and the 'merenda' (afternoon snack) culture",
    "focaccia_sig_5": "Historically baked on 'testi' (terracotta or metal discs) before modern pans",
    "focaccia_consum_1": "Eaten at any time of day: breakfast, lunch, snack, or dinner",
    "focaccia_consum_2": "Specifically enjoyed dipped in coffee or dry white wine (like Vermentino)",
    "focaccia_consum_3": "Sold in long strips or large rectangular pieces, often wrapped in wax paper",
    "focaccia_consum_4": "Eaten exclusively upside down (salt side down) to maximize flavor impact on the tongue",
    "focaccia_consum_5": "Commonly shared with friends at local bakeries (sciamadde) in Genoa",
    "focaccia_evo_1": "Ancient Times: Ligurians bake simple flatbreads on hot hearthstones",
    "focaccia_evo_2": "1500s: Use of yeast becomes common; the church tries to ban it during fasts to no avail",
    "focaccia_evo_3": "1800s: The 'Genoese Salami' (salamoia) brine technique is perfected",
    "focaccia_evo_4": "1900s: Industrial sheet pans become the standard, but the traditional 2cm height remains",
    "focaccia_evo_5": "2000s: Sourdough/Levain variations become popular among artisan bakers",
    "focaccia_evo_6": "Present: Global recognition as the benchmark for all oily flatbreads",
    "focaccia_ritual_1": "The 'Pizzicate' (Dimpling): using fingertips to create deep holes that trap pools of gold oil",
    "focaccia_ritual_2": "The Brine Bath: pouring 'la salamoia' over the dough just before the final proof",
    "focaccia_ritual_3": "Upside-Down Eating: the mandatory ritual of flipping the slice so the salt hits the taste buds first",
    "focaccia_ritual_4": "The Bread-Coffee Dip: a ritual that shocks outsiders but defines the Genoese morning",
    "focaccia_ritual_5": "Checking the Bottom: lifting the focaccia to ensure it is 'fried' golden by the oil in the pan",
    "focaccia_flavor_1": "Intense fruity bitterness and richness from Extra Virgin Olive Oil",
    "focaccia_flavor_2": "Sharp, crystalline salt bursts from the brine-filled dimples",
    "focaccia_flavor_3": "Mild wheat sweetness balanced with savory malt",
    "focaccia_flavor_4": "No sourness (if made traditionally); clean and focus on the oil",
    "focaccia_flavor_5": "Subtle herb notes if using traditional Ligurian toppings like rosemary",
    "focaccia_aroma_1": "Dominant aroma of warm, high-quality Ligurian olive oil",
    "focaccia_aroma_2": "Freshly baked white bread with a hint of toasted yeast",
    "focaccia_aroma_3": "Salty sea-air scent from the surface brine",
    "focaccia_aroma_4": "Herbal notes (rosemary or onion) if applicable",
    "focaccia_aroma_5": "Nutty, earthy wheat aromas",
    "focaccia_texture_1": "The 'Ligurian Crunch': a micro-thin, crispy top skin and fried bottom",
    "focaccia_texture_2": "Soft and sponge-like interior that 'wakes up' when bitten",
    "focaccia_texture_3": "Variable height - usually no more than 2cm (about 1 inch) thick",
    "focaccia_texture_4": "Contrasting pools of soft, salty center within the dimples",
    "focaccia_texture_5": "Extremely oily to the touch—your fingers should shine after eating",
    "focaccia_pair_1": "Beverage: Vermentino (white wine), dry Gin & Tonic, or Cappuccino for breakfast",
    "focaccia_pair_2": "Toppings: Sliced onions (Cipolle), fresh rosemary, or sage",
    "focaccia_pair_3": "Accompaniment: Ligurian olives (Taggiasca), mortadella, or soft stracchino cheese",
    "focaccia_pair_4": "Sauce: Never dipped in sauce; the oil and brine are the sauce",
    "focaccia_pair_5": "Dessert: Sometimes sprinkled with sugar (Focaccia Dolce) for a sweet variant",
    "focaccia_fe_1": "Fresh (0-2 hours): Peak perfection; the oil is vibrant and the crust is crisp",
    "focaccia_fe_2": "4-8 hours: The 'focaccia of the sailors'; becomes denser and chewier",
    "focaccia_fe_3": "Next Day: Best reheated in a pan to restore the 'fry' or cut into cubes for soup",
    "focaccia_fe_4": "Structural Loss: Will become 'soggy' if kept in plastic; must be kept in paper",
    "focaccia_fe_5": "Cold: A popular 'snack in the pocket' for hikers in the Cinque Terre",
    "focaccia_foundations_1": "Direct dough or mild preferment; long fermentation improves flavor.",
    "focaccia_foundations_2": "Hydration: 70-80%",
    "focaccia_di_1": "High hydration (70-80%) allows the dough to spread easily and creates a tender crumb",
    "focaccia_di_2": "Liberal oil in the dough (5-10%) and pan provides the signature 'fried' richness",
    "focaccia_di_3": "Long bulk fermentation (with folds) ensures flexibility for stretching and dimpling",
    "focaccia_di_4": "The use of malt or a small amount of sugar assists in browning despite the high oil film",
    "focaccia_di_5": "Minimal handling during the final stretch prevents degassing and maintains even height",
    "focaccia_bi_1": "Moderate heat (220-250°C) allows the oil to 'fry' the crust while keeping the center soft",
    "focaccia_bi_2": "Baking in a heavy-duty pan is mandatory to saturate the dough in oil bottom-up",
    "focaccia_bi_3": "The brine (water/oil/salt) creates 'micro-steam' in the dimples, preventing a hard crust",
    "focaccia_bi_4": "A relatively short 15-20 minute bake prevents excess drying of the thin loaf",
    "focaccia_bi_5": "Higher initial bottom heat is desirable to jumpstart the oil-frying reaction",
    "focaccia_bulk": "2–4 h at 23–25°C, possibly including cold retard",
    "focaccia_proof": "30–90 min in pan after dimpling and brine application",
    "focaccia_rv_1": "Focaccia di Recco - The paper-thin cheese-filled non-yeasted cousin",
    "focaccia_rv_2": "Focaccia con le Cipolle - Loaded with thin, sweet white onions (very traditional)",
    "focaccia_rv_3": "Focaccia di Voltri - A thinner, crunchier variant from the Voltri district of Genoa",
    "focaccia_rv_4": "Focaccia Barese - Apulian cousin using tomatoes, olives, and often boiled potatoes",
    "focaccia_rv_5": "Focaccia Veneta - Sweet, tall variant eaten during festivals like Christmas",
    "focaccia_cs_1": "Genoese Mistral (Cold/Dry): Use warm water (32°C) and cover pan with a damp cloth",
    "focaccia_cs_2": "Mediterranean Summer (Hot): Reduce yeast by 30% and perform bulk ferment in the fridge",
    "focaccia_cs_3": "Coastal Fog (High Humidity): Reduce water by 3-5% to prevent the dough from being too slack",
    "focaccia_cs_4": "High Altitude: Reduce yeast and sugar; the dough will rise too fast and lose 'oil-tension'",
    "focaccia_sc_1": "vs. Pizza: Focaccia is much oilier, has a brine finish, and is eaten at any time (including breakfast)",
    "focaccia_sc_2": "vs. Ciabatta: Both are hydrated, but Focaccia is an oil-enriched dough vs Ciabatta's lean dough",
    "focaccia_sc_3": "vs. Focaccia Barese: Genovese is thinner, focuses on oil/brine vs Barese's focus on toppings",
    "focaccia_sc_4": "vs. American Pan Pizza: Focaccia is less 'doughy' and has a unique salty/briny top vs dry cheese",
    "focaccia_ps_1": "Critical: Oil Quality - if the olive oil isn't excellent, the bread will be bland and greasy",
    "focaccia_ps_2": "Highly sensitive: Brine Ratio - too much water and it becomes soggy; too much salt is inedible",
    "focaccia_ps_3": "Dimple Depth: If you don't push through to the bottom, the oil pools will be shallow and evaporate",
    "focaccia_ps_4": "Flour Strength: Needs enough protein to resist the oil, but not so much that it becomes 'rubbery'",
    "focaccia_ps_5": "Proof Time in Pan: Under-proofing leads to 'tough' flatbread; it must be airy before the brine",
    "focaccia_risk_1": "The 'Leathery' Top: Caused by omitting the brine or not using enough steam in the oven",
    "focaccia_risk_2": "Greasy Mess: Using low-quality or rancid oil, or oil with a low smoke point",
    "focaccia_risk_3": "Sticking to Pan: Not using enough oil in the corners before panning",
    "focaccia_risk_4": "Salt Overdose: Forgeting that the brine contains salt and over-salting the dough itself",
    "focaccia_risk_5": "Dense Bottom: Oven floor not hot enough to start the oil-frying process quickly",
    "focaccia_note_1": "Don't be shy with the oil - if you're not making a mess, you're not doing it right",
    "focaccia_note_2": "Use Taggiasca olive oil if possible for the most authentic Ligurian flavor",
    "focaccia_note_3": "Turn the focaccia upside down on your plate so the salt hits your tongue first",
    "focaccia_note_4": "The brine should look like a milky emulsion of oil and water (salamoia)",
    "focaccia_note_5": "If using rosemary, push the needles into the dimples so they don't burn",
    "focaccia_faq_1_q": "What makes Focaccia Genovese unique?",
    "focaccia_faq_1_a": "The main feature is the 'salamoia' (brine) - a mixture of water, salt, and plenty of olive oil that is poured into the dimples of the dough before baking. This creates reservoirs of flavor and keeps the interior moist while the surface browns.",
    "focaccia_faq_2_q": "Is it true that Italians eat focaccia for breakfast?",
    "focaccia_faq_2_a": "Yes! In Genoa, it is a sacred ritual to dip a piece of warm Focaccia Genovese into cappuccino or caffè latte. The contrast of the salty oil with the sweet coffee is considered sublime by locals.",
    "focaccia_faq_3_q": "Why should I eat focaccia upside down?",
    "focaccia_faq_3_a": "It is a Genoese tradition. By flipping the salt side down, it hits the taste buds of the tongue first, providing a much more intense and immediate explosion of flavor.",
    "focaccia_faq_4_q": "What is the secret to perfect holes (dimples)?",
    "focaccia_faq_4_a": "Use your fingertips and press firmly against the pan, but without tearing the dough. These holes must be deep to 'hold' the oil and brine. If they are shallow, the brine evaporates and the bread dries out.",
    "focaccia_faq_5_q": "Can I use any olive oil?",
    "focaccia_faq_5_a": "You can, but since olive oil is the main flavor ingredient, the final result depends 100% on its quality. Fruity, extra virgin olive oils (especially from Liguria) are ideal for this style.",

    # Bagels Classic
    "bagels_intro": "Served with spreads like cream cheese and toppings such as smoked fish, widely found in bagel shops and bakeries.",
    "bagels_history": "Bagels originated in the Jewish communities of Poland in the 17th century, where they were traditionally given to women after childbirth. They migrated to New York City with Jewish immigrants in the late 19th century. The 'New York Style' Bagel was defined by the use of high-gluten flour and a mandatory boiling step in malted water, which creates the unique shiny, leathery crust and dense, chewy interior that distinguishes them from common rolls.",
    "bagels_sig_1": "The undisputed culinary icon of New York City and Jewish diaspora culture",
    "bagels_sig_2": "One of the few breads in the world where density is a positive quality marker",
    "bagels_sig_3": "Historically associated with 'Lox and Schmear' (smoked salmon and cream cheese)",
    "bagels_sig_4": "Symbol of late-night and early-morning urban life",
    "bagels_sig_5": "Protected by the 'Bagel Bakers Local 338' union in NY for decades, keeping the craft secret",
    "bagels_consum_1": "Traditionally served sliced vertically with cream cheese and toppings",
    "bagels_consum_2": "Available in 'Everything', 'Sesame', 'Poppy', and 'Cinnamon Raisin' varieties",
    "bagels_consum_3": "The 'Lox' Bagel (salmon, cream cheese, capers, onions, tomatoes) is the classic meal",
    "bagels_consum_4": "A staple for weekend family brunches in the Northeastern US",
    "bagels_consum_5": "In NY, customers often debate whether to 'toast' or 'not to toast' a fresh bagel",
    "bagels_evo_1": "1600s: First records of 'Beygls' in Krakow, Poland",
    "bagels_evo_2": "1910s: Bagel unions in NYC standardize the size (originally much smaller)",
    "bagels_evo_3": "1960s: Introduction of the automated bagel machine (Thompson) changes the industry",
    "bagels_evo_4": "1990s: Bagels become a global 'super-food', though quality often drops in mass production",
    "bagels_evo_5": "2000s: Resurgence of hand-rolled, wood-fired 'artisan' bagel shops in NY and Montreal",
    "bagels_evo_6": "Present: Global fusion bagels containing everything from rainbows to ube swirls",
    "bagels_ritual_1": "The Boiling Ritual: observing the 'float' when the bagels are dropped into malted boiling water",
    "bagels_ritual_2": "Hand-Rolling: the ritual of rolling a dough strip around the hand to create the seamless ring",
    "bagels_ritual_3": "The 'Everything' Shower: dredging the wet, boiled bagel through a mix of seeds and salt",
    "bagels_ritual_4": "The Schmear: applying a thick, generous layer of cream cheese from end to end",
    "bagels_ritual_5": "Checking the 'Hole': ensures it's tight enough to hold cream cheese but visible for boiling",
    "bagels_flavor_1": "Subtle malty sweetness from barley malt syrup (inside and in the boil)",
    "bagels_flavor_2": "Clean, high-quality toasted wheat",
    "bagels_flavor_3": "Savory and salty surface (especially seeds/everything mix)",
    "bagels_flavor_4": "Zero acidity (unless using sourdough), focusing on pure fermentative depth",
    "bagels_flavor_5": "Distinct 'leathery' toasted note from the boiled crust",
    "bagels_aroma_1": "Deep malt and honey-like notes",
    "bagels_aroma_2": "Toasted sesame and poppy seeds (standard varieties)",
    "bagels_aroma_3": "Freshly baked heavy bread",
    "bagels_aroma_4": "Smoky wood-fired notes (in traditional shops)",
    "bagels_aroma_5": "Nutty wheat aromas",
    "bagels_texture_1": "The 'NY Chew': extreme resistance when bitten, followed by a dense, moist finish",
    "bagels_texture_2": "Shiny, Leathery Crust: smooth, thin, and slightly tough due to the boiling step",
    "bagels_texture_3": "The 'Blisters': tiny micro-bubbles on the surface indicating long cold fermentation",
    "bagels_texture_4": "Dense Crumb: no large holes; a tight, uniform network that holds liquids well",
    "bagels_texture_5": "Structural Integrity: should be sturdy enough to hold significant toppings without bending",
    "bagels_pair_1": "Schmear: Full-fat cream cheese (Philadelphia style or artisanal)",
    "bagels_pair_2": "Protein: Smoked salmon (Lox), whitefish salad, or pastrami",
    "bagels_pair_3": "Vegetables: Capers, red onion, vine-ripe tomatoes, sliced cucumbers",
    "bagels_pair_4": "Breakfast: Bacon, egg, and cheese (BEC) on a bagel",
    "bagels_pair_5": "Beverage: Strong black coffee (NY deli style) or orange juice",
    "bagels_fe_1": "Warm (0-2 hours): Peak texture; the crust is at its most 'leathery' and the inside is soft-warm",
    "bagels_fe_2": "4-8 Hours: Becomes significantly firmer; this is the classic 'Deli Bagel' state",
    "bagels_fe_3": "Next Day: Must be toasted; toasting restores the aroma and softens the interior",
    "bagels_fe_4": "Day 3: Best used for bagel chips (thinly sliced and baked until dry)",
    "bagels_fe_5": "Freezing: Sliced bagels freeze exceptionally well and toast perfectly from frozen",
    "bagels_foundations_1": "Can be direct dough or use preferments; malt often included.",
    "bagels_foundations_2": "Hydration: 55-62%",
    "bagels_di_1": "Ultra-low hydration (55-62%) creates the required density and resistance ('chew')",
    "bagels_di_2": "High-Gluten Flour (13.5-14.5% protein) is essential to maintain the ring shape during boiling",
    "bagels_di_3": "Barley Malt Syrup provides the signature flavor and nutrients for yeast in the heavy dough",
    "bagels_di_4": "Minimal yeast works slowly during the mandatory 12-24h cold retard (bulk or shaped)",
    "bagels_di_5": "Tight rolling/shaping ensures no internal air pockets, creating the 'solid' bagel bite",
    "bagels_bi_1": "The Kettle Boil (30-60 sec) pre-gelatinizes the surface starch, creating the shiny, leathery crust",
    "bagels_bi_2": "Boiling in malted water (or with baking soda) provides the alkaline environment for browning",
    "bagels_bi_3": "High heat (220-250°C) is required to 'set' the dense dough quickly after the boil",
    "bagels_bi_4": "Baking on bagel boards (wet burlap) followed by flipping prevents a 'flat' bottom and ensures even bake",
    "bagels_bi_5": "A relatively long bake (15-20 mins) is needed to penetrate the dense, moist crumb",
    "bagels_bulk": "1–2 h at room temperature",
    "bagels_rv_1": "New York Style - The classic boiled, dense, and large modern version",
    "bagels_rv_2": "Montreal Style - Smaller, sweeter (honey-boiled), and baked in wood-fired ovens",
    "bagels_rv_3": "Jerusalem Bagel - Long, oval-shaped, softer, and usually topped with Za'atar",
    "bagels_rv_4": "St-Viateur/Fairmount - Specific Montreal sub-styles with distinct hand-rolled shapes",
    "bagels_rv_5": "Industrial Bagel - Steamed rather than boiled; lighter and more bread-like (not authentic)",
    "bagels_cs_1": "Dry NYC Winter: Use slightly warmer water (30°C) to help the low-hydration dough mix",
    "bagels_cs_2": "Hot/Humid Summer: Move shaped bagels to the fridge immediately to prevent over-proofing",
    "bagels_cs_3": "Coastal: The high humidity can make the boiled crust go 'soft/soggy'—extend the bake by 2 mins",
    "bagels_cs_4": "High Altitude: Reduce yeast and watch the boil time; they will expand and collapse faster",
    "bagels_sc_1": "vs. Montreal Bagel: NY is salt-boiled and larger/saltier; Montreal is honey-boiled and smaller/sweeter",
    "bagels_sc_2": "vs. Pretzel: Both are boiled/dipped in alkaline water, but Bagels are dense/lean vs. Pretzel's open/oily",
    "bagels_sc_3": "vs. Bread Roll: Bagels are boiled and low-hydration; rolls are direct-bake and high-hydration",
    "bagels_sc_4": "vs. Bialy: Bagels have a hole and are boiled; Bialys have a depression and are only baked",
    "bagels_ps_1": "Critical: Flour Protein - using regular All-Purpose will result in a soft, 'ordinary' bread roll",
    "bagels_ps_2": "Highly sensitive: Boil Time - too long and it won't rise in the oven; too short and it won't be shiny",
    "bagels_ps_3": "Cold Proofing: Skipping the 12h retard is the main reason for flavorless, 'commercial' bagels",
    "bagels_ps_4": "Barley Malt: Using sugar instead of malt changes the signature NYC deli flavor profile",
    "bagels_ps_5": "Dough Temperature: Keeping the dough 'cool' during mixing prevents premature yeast activity",
    "bagels_risk_1": "The 'Pancake' Bagel: Over-proofing before boiling leads to total collapse in the water",
    "bagels_risk_2": "Matte/Dull Surface: Not enough malt in the boiling water or the water wasn't fully boiling",
    "bagels_risk_3": "Raw Middle: Bake temperature too high, burning the outside while the dense center stays gummy",
    "bagels_risk_4": "Toughness (Too Hard): Using old flour or over-boiling beyond 90 seconds",
    "bagels_risk_5": "Hole Closing: Not stretching the center enough during shaping; it will close during the boil",
    "bagels_note_1": "If you don't have barley malt syrup, use honey or brown sugar (though it's less authentic)",
    "bagels_note_2": "Place the bagels in the fridge for at least 12 hours—this is where the flavor and blisters come from",
    "bagels_note_3": "Make the hole bigger than you think; it will shrink during the proof and the boil",
    "bagels_note_4": "Use a slotted spoon to flip them gently in the boiling water",
    "bagels_note_5": "Always seed them IMMEDIATELY after they come out of the water while they are still sticky",
    "bagels_faq_1_q": "What's the difference between a Bagel and regular bread rolls shaped like a ring?",
    "bagels_faq_1_a": "The secret of the Bagel is the boiling process before baking. Boiling the dough in water with malt (or honey) 'cooks' the surface, creating that shiny, elastic crust and preventing the bread from rising too much in the oven, keeping the interior dense and chewy.",
    "bagels_faq_2_q": "Is it really necessary to boil the Bagel?",
    "bagels_faq_2_a": "Yes! Without boiling, you'll just have a regular ring-shaped bread. Boiling gelatinizes the surface starch, ensuring the 'chewy' texture that is the hallmark of an authentic Bagel.",
    "bagels_faq_3_q": "What is the difference between New York and Montreal Bagels?",
    "bagels_faq_3_a": "The NY bagel is boiled in water with malt and salt, is larger, and has a denser, saltier texture. The Montreal bagel is smaller, boiled in honey water, contains no salt in the dough, and is strictly baked in wood-fired ovens, being sweeter and crunchier.",
    "bagels_faq_4_q": "Why does the Bagel have a hole in the middle?",
    "bagels_faq_4_a": "The hole serves two purposes: it increases surface area (helping the dense dough cook evenly and creating more crust) and, historically, allowed bakers to hang bagels on ropes or rods for transport and sale.",
    "bagels_faq_5_q": "Can I make Bagels with all-purpose flour?",
    "bagels_faq_5_a": "You can, but they will be too soft. An authentic Bagel requires 'high-gluten' (high protein) flour to withstand the boiling process and maintain that characteristic bite resistance.",

    # Croissant Classic
    "croissant_intro": "Eaten at breakfast and as a snack, produced in artisan and industrial bakeries worldwide.",
    "croissant_history": "Croissant is a laminated, yeasted dough with butter layers, becoming a symbol of French viennoiserie.",
    "croissant_sig_1": "Icon of French breakfast culture and café society worldwide",
    "croissant_sig_2": "Symbol of French culinary excellence and pastry craftsmanship",
    "croissant_sig_3": "Represents the French art of 'viennoiserie' - enriched, laminated pastries",
    "croissant_sig_4": "Cultural ambassador - croissants in cafés signal 'French-style' globally",
    "croissant_sig_5": "Embodies French dedication to technique, precision, and quality ingredients",
    "croissant_consum_1": "Classic French breakfast: croissant + café au lait or espresso",
    "croissant_consum_2": "Eaten at cafés, boulangeries, or taken home fresh in the morning",
    "croissant_consum_3": "Weekend treat and special occasion pastry, not everyday food for most French",
    "croissant_consum_4": "Business breakfast meetings, hotel continental breakfasts worldwide",
    "croissant_consum_5": "Best consumed within 4-6 hours of baking, never reheated or saved",
    "croissant_evo_1": "Legend: Inspired by Austrian kipferl, brought to France in 1770s by Marie Antoinette",
    "croissant_evo_2": "Reality: Modern croissant developed in Paris in early 1900s, not 1700s",
    "croissant_evo_3": "1906: August Zang's Viennese bakery in Paris popularizes laminated pastries",
    "croissant_evo_4": "1920s-1950s: Croissant becomes standardized in French bakeries",
    "croissant_evo_5": "1970s-1980s: Frozen croissant dough industrializes production, quality varies",
    "croissant_evo_6": "2000s-present: Artisan revival, emphasis on all-butter, hand-laminated croissants",
    "croissant_ritual_1": "The crescent shape (croissant au beurre) vs straight (ordinaire/margarine) distinction",
    "croissant_ritual_2": "Tearing apart to reveal honeycomb interior - visual quality check",
    "croissant_ritual_3": "Dipping in café au lait or hot chocolate - traditional French breakfast ritual",
    "croissant_ritual_4": "The flaky shower of crumbs is expected and accepted - sign of proper lamination",
    "croissant_ritual_5": "Warm from oven vs room temperature debate - purists prefer slight warmth",
    "croissant_flavor_1": "Rich, creamy butter with subtle cultured dairy tang",
    "croissant_flavor_2": "Delicate yeast and fermentation notes from enriched dough",
    "croissant_flavor_3": "Subtle sweetness from sugar, balanced by butter's richness",
    "croissant_flavor_4": "Toasted, caramelized notes from golden-brown crust",
    "croissant_flavor_5": "Clean wheat flavor from quality flour, enhanced by butter",
    "croissant_aroma_1": "Intense butter aroma - warm, nutty, slightly sweet",
    "croissant_aroma_2": "Yeasty, bread-like fermentation scents",
    "croissant_aroma_3": "Caramelized, toasted notes from baking",
    "croissant_aroma_4": "Hint of vanilla or cultured cream from quality butter",
    "croissant_aroma_5": "Overall: irresistible, bakery-fresh pastry aroma",
    "croissant_texture_1": "Shatteringly crispy, flaky exterior with visible layers",
    "croissant_texture_2": "Honeycomb interior structure with distinct, airy layers",
    "croissant_texture_3": "Tender, almost melting texture from butter between layers",
    "croissant_texture_4": "Delicate crumb that pulls apart in sheets, not chunks",
    "croissant_texture_5": "Overall: crispy-tender contrast, light yet rich, never dense or doughy",
    "croissant_pair_1": "Classic: Plain with café au lait, espresso, or hot chocolate",
    "croissant_pair_2": "Traditional: Butter and jam (though purists say unnecessary)",
    "croissant_pair_3": "Savory: Ham and cheese (croissant jambon-fromage)",
    "croissant_pair_4": "Sweet: Almond cream filling (croissant aux amandes)",
    "croissant_pair_5": "Avoid: Heavy fillings that mask the butter and lamination - simplicity is key",
    "croissant_fe_1": "Fresh from oven (0-2 hours): Peak flakiness, butter aroma intense, layers crispy",
    "croissant_fe_2": "2-4 hours: Still excellent, layers soften slightly, flavors meld beautifully",
    "croissant_fe_3": "4-6 hours: Texture declines, layers merge, still acceptable but past prime",
    "croissant_fe_4": "After 6 hours: Stale, tough, layers compressed - use for bread pudding or almond croissants",
    "croissant_fe_5": "Reheated: Never recommended - destroys flaky texture, butter leaks out",
    "croissant_foundations_1": "Usually straight dough; some use poolish.",
    "croissant_foundations_2": "Hydration: 50-60%",
    "croissant_di_1": "Low hydration (50-60%) creates firm dough that can withstand multiple folds without tearing",
    "croissant_di_2": "Lamination with butter (50% of flour weight) creates distinct flaky layers",
    "croissant_di_3": "Enrichment with milk, sugar, and butter in dough provides tender, rich base",
    "croissant_di_4": "Cold retardation between folds keeps butter solid, preventing mixing with dough",
    "croissant_di_5": "Strong flour (W 280-320) provides structure to support butter layers during proofing and baking",
    "croissant_bi_1": "Moderate temperature (190-210°C) allows butter to melt gradually, creating steam between layers",
    "croissant_bi_2": "Steam from butter creates dramatic lift and separation of layers (honeycomb structure)",
    "croissant_bi_3": "Proper proofing (2-3h at 24-26°C) is critical - under-proofed croissants are dense, over-proofed collapse",
    "croissant_bi_4": "Egg wash creates glossy, golden-brown surface and seals edges",
    "croissant_bi_5": "Baking time (15-20 min) must be sufficient to fully cook interior while achieving deep color",
    "croissant_bulk": "1–2 h at 24–26°C",
    "croissant_proof": "2–3 h at 24–26°C after shaping",
    "croissant_rv_1": "Croissant au Beurre - Made with pure butter, crescent shape (traditional French)",
    "croissant_rv_2": "Croissant Ordinaire - Made with margarine, straight shape (commercial)",
    "croissant_rv_3": "Croissant aux Amandes - Filled with almond cream, topped with almonds",
    "croissant_rv_4": "Pain au Chocolat - Same dough, rectangular shape with chocolate batons",
    "croissant_rv_5": "Pain aux Raisins - Rolled with pastry cream and raisins",
    "croissant_cs_1": "Hot/Humid (>25°C, >70% RH): Work in air-conditioned space (18-20°C), use European butter (higher melting point), reduce proof time by 30%",
    "croissant_cs_2": "Cold/Dry (<15°C, <40% RH): Butter may be too hard - let warm slightly before laminating, extend proof time by 20-30%",
    "croissant_cs_3": "Tropical: Nearly impossible without climate control - butter melts into dough. Use 16-18°C workspace, freeze dough between folds",
    "croissant_cs_4": "High Altitude (>1500m): Reduce yeast by 10-15%, increase liquid slightly, proof time may be shorter",
    "croissant_sc_1": "vs. Danish Pastry: Croissant has more folds (typically 27 layers), less sugar, no eggs in lamination",
    "croissant_sc_2": "vs. Puff Pastry: Croissant is yeasted (leavened), enriched dough, Danish is unleavened, neutral dough",
    "croissant_sc_3": "vs. Brioche: Croissant is laminated with external butter, brioche has butter mixed into dough",
    "croissant_sc_4": "vs. Pain au Lait: Croissant is laminated and flaky, pain au lait is enriched but soft and tender",
    "croissant_ps_1": "Critical: Butter temperature during lamination must be 15-18°C - too cold cracks, too warm mixes into dough",
    "croissant_ps_2": "Highly sensitive to proof temperature and time - 24-26°C for 2-3h is ideal, variance causes collapse or density",
    "croissant_ps_3": "Dough temperature during lamination: must stay below 18°C to prevent butter melting",
    "croissant_ps_4": "Number of folds affects texture: 3 single folds (27 layers) is standard, more creates dense texture, fewer creates thick layers",
    "croissant_ps_5": "Oven temperature critical: below 190°C butter leaks out, above 210°C exterior burns before interior cooks",
    "croissant_risk_1": "Butter breakthrough: Butter melts into dough during lamination - caused by warm dough or butter",
    "croissant_risk_2": "Collapsed layers: Over-proofing causes butter to leak and layers to merge",
    "croissant_risk_3": "Dense, bread-like texture: Under-lamination, insufficient folds, or butter too cold and cracked",
    "croissant_risk_4": "Butter leakage during baking: Oven too cool, dough over-proofed, or poor sealing of edges",
    "croissant_risk_5": "Uneven layers: Inconsistent rolling pressure, dough not relaxed enough between folds",
    "croissant_note_1": "Traditional French croissants are crescent-shaped (au beurre), straight ones indicate margarine (ordinaire)",
    "croissant_note_2": "Lamination creates approximately 27 layers with 3 single folds (3x3x3)",
    "croissant_note_3": "European-style butter (82-84% fat) is preferred over American (80% fat) for better lamination",
    "croissant_note_4": "Croissants should be eaten within 4-6 hours of baking for optimal texture",
    "croissant_note_5": "The honeycomb interior structure is the hallmark of proper lamination and proofing",
    "croissant_flour_strength": "Strong bread or pastry flour suitable for lamination (W 280-320)",
    "croissant_faq_1_q": "Why did my butter break through the dough during lamination?",
    "croissant_faq_1_a": "Butter breakthrough occurs when the butter is too soft or the dough is too warm. Both should be around 15-18°C during lamination - firm but pliable. If butter is warmer than dough, it will melt and mix in. If butter is too cold, it will crack and break through. Work in a cool environment (18-20°C) and refrigerate dough between folds if needed. Use European butter (82-84% fat) for better plasticity.",
    "croissant_faq_2_q": "How do I know when croissants are properly proofed?",
    "croissant_faq_2_a": "Properly proofed croissants should be visibly larger (nearly doubled), feel light and airy when gently lifted, and show a slight jiggle when the pan is shaken. The layers should be visible and separated. If you gently press with a finger, the dough should slowly spring back but leave a slight indentation. Under-proofed croissants are dense and small; over-proofed ones collapse during baking and leak butter.",
    "croissant_faq_3_q": "What's the difference between 3 single folds and 2 double folds?",
    "croissant_faq_3_a": "3 single folds (letter folds) create 27 layers (3×3×3), while 2 double folds (book folds) create 16 layers (4×4). The 3 single fold method is traditional French technique, creating more numerous, thinner layers with better separation. The 2 double fold method is faster but creates thicker, fewer layers. For classic croissants, use 3 single folds. Each fold requires 30-60 minutes rest in refrigerator.",
    "croissant_faq_4_q": "Can I make croissants without a sheeter or rolling pin?",
    "croissant_faq_4_a": "A rolling pin is essential for croissant lamination - you cannot achieve the thin, even layers needed without one. A sheeter (dough roller machine) makes the process easier and more consistent but is not necessary. Use a heavy French-style rolling pin without handles for best control. Roll with even pressure, working from center outward, and rotate dough 90° between passes to maintain rectangular shape.",
    "croissant_faq_5_q": "Why are my croissants dense and bread-like instead of flaky?",
    "croissant_faq_5_a": "Dense croissants indicate one of several issues: 1) Insufficient lamination - need 3 complete single folds for 27 layers, 2) Butter was too cold and cracked instead of staying pliable, 3) Over-mixing of dough developed too much gluten, 4) Under-proofing - didn't allow enough time for yeast to create lift, 5) Oven temperature too low - butter leaked out instead of creating steam. Ensure all steps are followed precisely.",
    "croissant_faq_6_q": "Should I use salted or unsalted butter for lamination?",
    "croissant_faq_6_a": "Always use unsalted butter for lamination. Salted butter contains water and salt which interfere with the lamination process and can create uneven layers. European-style unsalted butter with 82-84% fat content is ideal - it has less water than American butter (80% fat), making it more plastic and easier to laminate. The dough itself contains salt for flavor."
}

data.update(new_keys)

# Sort keys alphabetically
sorted_data = dict(sorted(data.items()))

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(sorted_data, f, indent=2, ensure_ascii=False)

print(f"Added {len(new_keys)} keys to styles.json.")
