import json
import os

file_path = r'c:\Users\eduar\OneDrive\Desktop\Antigravity\doughlabpro\public\locales\en\styles.json'

with open(file_path, 'r', encoding='utf-8') as f:
    data = json.load(f)

new_keys = {
    # Arepa
    "arepa_intro": "Griddled, baked or fried, then split and filled with a wide range of savory fillings.",
    "arepa_history": "Arepas have been the cornerstone of the indigenous diets of Northern South America (Venezuela and Colombia) for thousands of years, predating the arrival of the Spanish. Traditionally, the process was labor-intensive: women would hull, boil, and hand-grind the corn into 'masa' on stone metates. A major culinary shift occurred in the 1960s with the invention of 'Masarepa' (pre-cooked, dehydrated corn flour), which allowed families to prepare arepas in minutes. Today, the arepa is a powerful cultural identifier for both Venezuelans and Colombians, each with their own distinct rituals and variations.",
    "arepa_sig_1": "The 'Daily Bread' and primary nutritional staple of Venezuela and Colombia",
    "arepa_sig_2": "A symbol of family unit and heritage—the act of 'making' arepas is central to the home",
    "arepa_sig_3": "Technically unique: relies on gelatinized starch (Masarepa) rather than gluten or leavening",
    "arepa_sig_4": "A vessel for creativity: thousands of registered filling combinations (Venezuelan Reyes)",
    "arepa_sig_5": "Represents the endurance of pre-Hispanic corn culture in a modern wheat-dominated world",
    "arepa_consum_1": "Colombian Style: often served flat, topped with cheese or butter as a side to breakfast",
    "arepa_consum_2": "Venezuelan Style: thick and split like a pocket, stuffed with elaborate savory fillings",
    "arepa_consum_3": "Eaten at every meal: breakfast (with eggs), lunch (with roast beef), and dinner (with cheese)",
    "arepa_consum_4": "Street Food Icon: available at 24/7 'Areperas' in major cities",
    "arepa_consum_5": "The 'Reina Pepiada': the most famous filling (shredded chicken, avocado, and mayo)",
    "arepa_evo_1": "1000 BCE: Indigenous tribes in the Andes and coastal regions cultivate and grind corn for arepas",
    "arepa_evo_2": "1500s: Spanish colonists adopt the arepa as a superior alternative to hard ship's biscuit",
    "arepa_evo_3": "1960: Dr. Luis Caballero Mejías patented pre-cooked corn flour, revolutionary for home cooks",
    "arepa_evo_4": "2010s: The Venezuelan diaspora carries the Arepa to the global stage as a gourmet gluten-free staple",
    "arepa_evo_5": "Present: High focus on corn biodiversity and using local, non-GMO heirloom varieties",
    "arepa_evo_6": "Future: Integration into universal healthy-dining circuits as a high-fiber wheat alternative",
    "arepa_ritual_1": "The 'Clapping' Sound: the rhythmic hand-clapping used to shape the dough into a perfect disc",
    "arepa_ritual_2": "The Budare: the traditional cast-iron or clay griddle used to sear the crust",
    "arepa_ritual_3": "Finger-Pressing: testing the dough for the perfect 'earlobe' consistency",
    "arepa_ritual_4": "The 'Hollow Thump': tapping the crust to hear if the inside has steamed into a separate pocket",
    "arepa_ritual_5": "The 'Opening': using a sharp knife to carefully split the hot arepa halfway for stuffing",
    "arepa_flavor_1": "Intense toasted corn sweetness",
    "arepa_flavor_2": "Savory, slightly earthy grain notes",
    "arepa_flavor_3": "Mildly floral and nutty finish",
    "arepa_flavor_4": "Buttery or salty undertones (depending on mix-ins)",
    "arepa_flavor_5": "Neutral but hearty canvas that emphasizes the fat of the filling",
    "arepa_aroma_1": "Warm toasted corn / popcorn",
    "arepa_aroma_2": "Freshly ground grain",
    "arepa_aroma_3": "Sun-baked earth",
    "arepa_aroma_4": "Buttery and milky (if cheese or milk is added to dough)",
    "arepa_aroma_5": "Deeply caramelized crust (if grilled dark)",
    "arepa_texture_1": "Contrast: crispy, thin external skin vs. soft, moist, and pillowy interior",
    "arepa_texture_2": "Granular yet smooth: the unique mouthfeel of ground pre-cooked corn",
    "arepa_texture_3": "Moist and Hydrating: never dry if cooked correctly; the inside should feel 'lush'",
    "arepa_texture_4": "Non-Elastic: easy to bite through with no 'pull' or rubberiness",
    "arepa_texture_5": "Substantial: despite being small, it is a very dense and filling bread",
    "arepa_pair_1": "Venezuelan Filling: 'Reina Pepiada' (chicken/avocado) or 'Pabellón' (shredded beef/beans/plantains)",
    "arepa_pair_2": "Colombian Topping: Salted butter and melted Queso Campesino or Mozzarella",
    "arepa_pair_3": "Fat: Avocado slices, fresh farmer's cheese, or creamy mayonnaise",
    "arepa_pair_4": "Drink: Hot Chocolate (Santafereño style), coffee with milk, or fresh fruit juice",
    "arepa_pair_5": "Snack: Chicharrón (fried pork belly) or spicy Venezuelan 'Ajicero' (chili oil)",
    "arepa_fe_1": "Fresh (0-15 mins): Maximum contrast between crisp crust and steaming interior",
    "arepa_fe_2": "1-Way Street: Once cool, the corn starch sets and becomes firm",
    "arepa_fe_3": "Next Day: Must be toasted or grilled to restore the 'melt' of the interior",
    "arepa_fe_4": "Stale: Traditionally sliced into strips and fried (Arepa chips)",
    "arepa_fe_5": "Freezing: Dough or cooked arepas freeze perfectly; reheat directly on a griddle",
    "arepa_foundations_1": "None; relies on precooked corn flour hydration.",
    "arepa_foundations_2": "Hydration: 60-75%",
    "arepa_di_1": "Pre-cooked Corn Flour (Masarepa) is non-negotiable; traditional corn meal will not bind",
    "arepa_di_2": "Water-to-Flour ratio (usually 1.2 : 1) must be precise to achieve the 'earlobe' soft texture",
    "arepa_di_3": "No gluten: the dough is held together by the gelatinized starches of the pre-cooked corn",
    "arepa_di_4": "Resting (5-10 mins) is vital to allow the dehydrated corn grains to fully swell with water",
    "arepa_di_5": "Inclusion of 5-10% cheese or butter in the dough is a common variation for extra richness",
    "arepa_bi_1": "Initial Searing (Budare/Griddle) creates the protective crust that prevents the inside from drying",
    "arepa_bi_2": "Finishing in the Oven (10-12 mins) allows the internal steam to build a 'hollow' pocket for filling",
    "arepa_bi_3": "High heat (220°C+) is needed for the iconic dark 'leopard spots' on the corn surface",
    "arepa_bi_4": "Cooking in a pan with a lid (low heat) is a common home technique to ensure a moist interior",
    "arepa_bi_5": "The lack of yeast means the 'rise' is entirely dependent on internal steam expansion",
    "arepa_rv_1": "Arepa Rumbera - High-flavor Venezuelan variant filled with roast pork and cheese",
    "arepa_rv_2": "Arepa de Huevo - Deep-fried Colombian specialty containing a whole cooked egg inside",
    "arepa_rv_3": "Arepa Dulce - Sweet versions using anise and brown sugar (Piloncillo/Papelón)",
    "arepa_rv_4": "Arepa de Choclo - Made with fresh sweet corn, resulting in a pancake-like consistency",
    "arepa_rv_5": "Arepa de Trigo - A wheat-based version from the Andean mountain regions",
    "arepa_cs_1": "High Humidity: The corn dough will hydrate faster; reduce water by 2% to avoid stickiness",
    "arepa_cs_2": "Arid/Dry: The dough will crack on the edges during shaping; keep a bowl of water to dip hands",
    "arepa_cs_3": "Tropical Heat: Fresh fillings will spoil fast; keep the arepa hot but the fillings chilled until serving",
    "arepa_cs_4": "Cold/Winter: Use warm water (40°C) to hydrate the Masarepa for a smoother, more plastic dough",
    "arepa_sc_1": "vs. Corn Tortilla: Arepas are much thicker and use pre-cooked flour vs. nixtamalized raw masa",
    "arepa_sc_2": "vs. English Muffin: Similar 'split and fill' format, but Arepas are corn-based and gluten-free",
    "arepa_sc_3": "vs. Pupusa: Pupusas are stuffed *before* cooking; Arepas are stuffed *after* splitting",
    "arepa_sc_4": "vs. Gordita: Gorditas are wheat or corn-based and deep-fried; Arepas are typically griddled",
    "arepa_ps_1": "Critical: Water Ratio - 5ml too little and it cracks; 5ml too much and it won't hold its disc shape",
    "arepa_ps_2": "Highly sensitive: Surface Temp - too low and the arepa dries out before developing a crust",
    "arepa_ps_3": "Resting time: Skipping the 10-min hydration leads to a 'gritty' mouthfeel in the finished bread",
    "arepa_ps_4": "Thickness: A 1.5 - 2cm thickness is required for Venezuelan splitting; Colombian is thinner (1cm)",
    "arepa_ps_5": "Purity of Flour: Yellow corn flour is sweeter and earthier; White corn is cleaner and more neutral",
    "arepa_risk_1": "The Crack: Edges splitting during shaping (due to dry dough or lack of hand-wetting)",
    "arepa_risk_2": "Raw Center: Griddle was too hot, searing the outside while leaving the inside gummy",
    "arepa_risk_3": "Broken Pocket: Trying to split the arepa while it's too cool or with a dull knife",
    "arepa_risk_4": "Leathery Skin: Leaving the arepa on the griddle too long at low heat",
    "arepa_risk_5": "Masa-Bolas: Dry clumps of flour inside the dough (not whisking water properly during mixing)",
    "arepa_note_1": "Always start with water in the bowl, then add the flour—never the other way around",
    "arepa_note_2": "Use your palms to round the edges of the disc to prevent 'mountain ridges' that burn",
    "arepa_note_3": "If you want them extra crispy, finish them for 5 minutes at 200°C in a convection oven",
    "arepa_note_4": "Look for the 'P.A.N.' brand—it is the global standard for authentic pre-cooked corn flour",
    "arepa_note_5": "Keep a bowl of salted water nearby to wet your hands constantly while shaping",
    "arepa_faq_1_q": "What is the difference between Venezuelan and Colombian Arepas?",
    "arepa_faq_1_a": "Generally, Venezuelan arepas are thicker and designed to be split open and stuffed with various savory fillings (like a sandwich). Colombian arepas are often thinner, less focused on stuffing, and usually served as a side or topped with cheese and butter.",
    "arepa_faq_2_q": "Can I use cornmeal or corn flour for corn dogs to make Arepas?",
    "arepa_faq_2_a": "No. Arepas must be made with 'Masarepa' (pre-cooked corn flour). Regular cornmeal is raw and won't bind into a dough with just water; it will crumble. Look for 'P.A.N.' or 'Harina Juana' in the supermarket.",
    "arepa_faq_3_q": "Are Arepas gluten-free?",
    "arepa_faq_3_a": "Yes! Authentic arepas are made with 100% corn flour, which is naturally gluten-free. This has made them extremely popular globally as a healthy bread alternative. Just ensure there is no cross-contamination if you are highly sensitive.",
    "arepa_faq_4_q": "Why did my arepas crack on the edges when I shaped them?",
    "arepa_faq_4_a": "Cracking is a sign that the dough is too dry. Add a few more tablespoons of water and knead it for another minute. Also, keep your hands wet while shaping; the moisture from your palms helps create a smooth, crack-free edge.",
    "arepa_faq_5_q": "How do I know when the arepa is fully cooked inside?",
    "arepa_faq_5_a": "Use the 'Thump Test'. Pick up the arepa and tap the center with your finger. It should sound hollow. Also, a well-cooked arepa will feel light for its size and the crust will be firm and slightly springy.",

    # Heirloom
    "heirloom_intro": "Produced by small mills, micro-bakeries and advanced home bakers focusing on grain diversity.",
    "heirloom_history": "Heirloom Grain Levain represents the 'Third Wave' of artisan baking, which prioritizes biodiversity and soil health over the industrial standardization of wheat. Historically, thousands of wheat varieties existed regionally across the globe, but the Green Revolution of the mid-20th century narrowed these down to a few high-yield, short-stalk varieties. In the early 21st century, a movement led by farmers and bakers began reviving ancient and heritage grains like Emmer, Einkorn, Spelt, and Turkey Red. These loaves use stone-ground flours and natural leaven to express the 'terroir' of the land where the grain was grown, reclaiming the nutritional and flavor complexity lost in industrial milling.",
    "heirloom_sig_1": "A culinary manifestation of the 'Slow Food' and Regenerative Agriculture movements",
    "heirloom_sig_2": "Celebrates 'Inclusivity' of modern baking—honoring the unique genetics of each grain",
    "heirloom_sig_3": "Technically demanding: requires the baker to listen to the grain rather than follow a formula",
    "heirloom_sig_4": "Represents the bridge between modern microbiology (sourdough) and ancient botany",
    "heirloom_sig_5": "Regarded as the 'Top-Shelf' of the sourdough world, often command premium prices",
    "heirloom_consum_1": "Ideally consumed as a standalone experience with premium salted butter or extra virgin olive oil",
    "heirloom_consum_2": "Served at high-end farm-to-table restaurants as a signature table bread",
    "heirloom_consum_3": "Commonly featured in 'Bread and Cheese' pairings, similar to wine tastings",
    "heirloom_consum_4": "Sold through micro-bakeries, CSA shares, and specialized artisan markets",
    "heirloom_consum_5": "Often given as a high-value gift among culinary enthusiasts",
    "heirloom_evo_1": "Pre-1900s: Thousands of regional wheat varieties are grown globally",
    "heirloom_evo_2": "1950s-70s: The Green Revolution standardizes wheat for yield and herbicide resistance",
    "heirloom_evo_3": "1990s: Pioneers like Fred Kirschenmann and Glenn Roberts begin saving heirloom seeds",
    "heirloom_evo_4": "2010s: Modernist bakers (e.g., Tartine, Elmore Mountain) shift focus toward local, stone-ground grains",
    "heirloom_evo_5": "Present: Global resurgence of 'Regional Grain Hubs' and mill-to-bakery supply chains",
    "heirloom_evo_6": "Future: Use of perennial grains (like Kernza) in heirloom-style levain loaves",
    "heirloom_ritual_1": "The 'Grain Scouring': inspecting the whole berries for color and aroma before milling",
    "heirloom_ritual_2": "Stone-Milling: the ritual of grinding grain fresh to preserve volatile oils and nutrients",
    "heirloom_ritual_3": "The 'Feel' Test: assessing the fragile gluten strength of heritage grains during bulk",
    "heirloom_ritual_4": "Natural Stencil: dusting the loaf with flour and using wheat stalks to score meaningful designs",
    "heirloom_ritual_5": "The 'Terroir' Assessment: identifying specific flavor notes (cinnamon, pepper, grass) in the finished bread",
    "heirloom_flavor_1": "Deeply nutty and buttery with high cereal sweetness",
    "heirloom_flavor_2": "Complex earthy notes (reminiscent of wet stone or damp soil)",
    "heirloom_flavor_3": "Subtle spice notes: cinnamon (Einkorn), black pepper (Rye), or honey (Spelt)",
    "heirloom_flavor_4": "Vibrant fruitiness from long-fermented whole grains",
    "heirloom_flavor_5": "Bold, toasted-hazelnut crust flavor",
    "heirloom_aroma_1": "Warm toasted walnuts and sunflower seeds",
    "heirloom_aroma_2": "Freshly turned earth and fermented grass",
    "heirloom_aroma_3": "Caramel and dark honey",
    "heirloom_aroma_4": "Wildflower and hay",
    "heirloom_aroma_5": "Warm yeast and lactic tang",
    "heirloom_texture_1": "Hearty and Substantial: a rich, 'alive' mouthfeel with significant chew",
    "heirloom_texture_2": "Creamy, Custardy Crumb: the high oil content of heirloom grains yields a moist interior",
    "heirloom_texture_3": "Varying Alveoli: usually a more closed, even crumb due to fragile gluten networks",
    "heirloom_texture_4": "Rustic, Thick Crust: often baked dark to emphasize the inherent minerals of the grain",
    "heirloom_texture_5": "Grain Specks: visible pieces of the germ and bran add a pleasant rustic texture",
    "heirloom_pair_1": "Fat: Grass-fed butter, cold-pressed sunflower oil, or sheep's milk ricotta",
    "heirloom_pair_2": "Acid: Pickled vegetables, fermented hot sauces, or sharp apple cider",
    "heirloom_pair_3": "Sweet: Wildflower honey, dark chocolate shavings, or roasted figs",
    "heirloom_pair_4": "Drink: Unfiltered craft ale, earthy red wine (Pinot Noir), or roasted dandelion root tea",
    "heirloom_pair_5": "Dish: Bone marrow on toast, roasted root vegetables, or hearty oxtail stew",
    "heirloom_fe_1": "Fresh (0-12 hours): Peak aroma and softest crumb; best for eating with only butter",
    "heirloom_fe_2": "Day 2: Flavors deepen; the 'grain-forward' notes become more pronounced",
    "heirloom_fe_3": "Day 4: Outstanding for toasting; the complex starches caramelize beautifully",
    "heirloom_fe_4": "Day 6: Still moist; excellent with soups and stews",
    "heirloom_fe_5": "Stale: Traditionally transformed into 'Bread Salad' (Panzanella) or premium croutons",
    "heirloom_foundations_1": "Levain 20–30%, often adjusted to grain mix.",
    "heirloom_foundations_2": "Hydration: 75-85%",
    "heirloom_di_1": "Stone-ground heirloom grains contain the Germ and Bran, which accelerate fermentation significantly",
    "heirloom_di_2": "Fragile Gluten: Heritage grains often have a lower 'Tenacity' (strength), requiring gentle handling",
    "heirloom_di_3": "High enzymatic activity can lead to a sticky dough if the fermentation temperature is too high",
    "heirloom_di_4": "Water absorption (75-90%) varies wildly—the baker must 'feel' the hydration for each new batch of grain",
    "heirloom_di_5": "Natural leaven (Levain) is used to soften the bran and make the minerals more bio-available",
    "heirloom_bi_1": "High initial heat (240-250°C) is required to 'catch' the oven spring of weaker-gluten grains",
    "heirloom_bi_2": "Steam is vital for the first 20 minutes to prevent the mineral-heavy crust from setting too early",
    "heirloom_bi_3": "A 'Bold' bake (dark brown/mahogany) is preferred to fully develop the complex grain sugars",
    "heirloom_bi_4": "Immediate removal from the oven is necessary to preserve the thin, toasted bottom crust",
    "heirloom_bi_5": "Cooling for at least 4 hours is mandatory; these breads continue to 'set' and mature as they cool",
    "heirloom_rv_1": "Single-Varietal Einkorn - The 'Father of Wheat'; very yellow, nutty, and delicate",
    "heirloom_rv_2": "Spelt Sourdough - Ancient German staple, sweet and nutty with slightly stronger gluten",
    "heirloom_rv_3": "Turkey Red Heritage - The classic 19th-century American bread wheat; bold and savory",
    "heirloom_rv_4": "Marquis Sourdough - An early 20th-century Canadian heritage grain with excellent milling quality",
    "heirloom_rv_5": "Heirloom Rye Blend - Using ancient landrace rye varieties for deep earthiness",
    "heirloom_cs_1": "Arid/Dry Environment: The fiber-rich dough will dry fast; keep covered at all times",
    "heirloom_cs_2": "High Humidity: Crust can become soft; leave in a turned-off oven for 10 mins post-bake",
    "heirloom_cs_3": "Tropical Heat: High enzymes in heirloom flour will lead to 'over-proof' in under 3 hours",
    "heirloom_cs_4": "Cold/Winter: Ideal for the slow, enzymatic development required for these sensitive grains",
    "heirloom_sc_1": "vs. Tartine Country: Heirloom uses 50-100% heritage grains vs. Tartine's typically lower whole grain %",
    "heirloom_sc_2": "vs. Baguette: Worlds apart; focuses on grain density and nutrition vs Baguette's light starch/air",
    "heirloom_sc_3": "vs. 100% Whole Wheat: Heirloom focuses on 'Variety' and 'Terroir' vs 'Whole Wheat' generic category",
    "heirloom_sc_4": "vs. Pumpernickel: Heirloom is a lighter, aerated sourdough vs. Pumpernickel's dense, scalded mash",
    "heirloom_ps_1": "Critical: Mixing Time - over-mixing will destroy the fragile gluten of Einkorn or Spelt",
    "heirloom_ps_2": "Highly sensitive: Temperature - high temps activate enzymes too fast, leading to a gummy interior",
    "heirloom_ps_3": "Milling Freshness: Stone-ground flour loses its flavor profile within days; fresh is best",
    "heirloom_ps_4": "Salt Level: 2-2.2% is required to balance the intense flavors of heritage germ and bran",
    "heirloom_ps_5": "Proofing: 80% proof is safer than 100% for these grains to ensure the loaf doesn't collapse",
    "heirloom_risk_1": "The 'Brick': Dough collapsed during baking due to weak gluten or over-proofing",
    "heirloom_risk_2": "Gummy 'Gray' Crumb: Too much hydration or under-baked interior for the grain weight",
    "heirloom_risk_3": "Bitter Finish: Over-fermented whole grains or using oxidized (old) stone-ground flour",
    "heirloom_risk_4": "Dull Crust: Oven temperature too low or lack of steam during the initial spring",
    "heirloom_risk_5": "Sticky Paste: Too much handling of heritage grains after the bulk fermentation starts",
    "heirloom_note_1": "Consider a 'Sifted' heritage flour for the first 50% of the recipe to give the loaf more lift",
    "heirloom_note_2": "Always perform an Autolyse (30-60 mins) to fully hydrate the bran before adding salt/levain",
    "heirloom_note_3": "Gentle coil-folds are much better for heritage gluten than aggressive stretch-and-folds",
    "heirloom_note_4": "If the grain is very weak, bake it in a preheated Dutch Oven to provide structural support",
    "heirloom_note_5": "Score deeply (at least 1.5cm) to help the heavy whole-grain dough expand vertically",
    "heirloom_faq_1_q": "What exactly makes a grain 'Heirloom' or 'Heritage'?",
    "heirloom_faq_1_a": "Heirloom grains are varieties of wheat (like Turkey Red or Marquis) that were grown before the industrial revolution and 'Green Revolution' of the 1950s. They haven't been cross-bred for high yields or mechanical harvesting, meaning they retain their original flavor profiles, deeper root systems, and higher mineral content.",
    "heirloom_faq_2_q": "Why is the dough so much harder to handle than regular bread flour?",
    "heirloom_faq_2_a": "Heritage grains often have 'extensible' but not 'tenacious' gluten. This means they stretch easily but don't hold their shape as well as modern, high-protein bread wheats. They also contain more bran and germ, which can physically cut the gluten strands if the dough is handled too roughly.",
    "heirloom_faq_3_q": "Is Heirloom Levain healthier than regular sourdough?",
    "heirloom_faq_3_a": "Generally, yes. These grains are often stone-ground, which preserves the germ (where the oils and vitamins are). Long sourdough fermentation makes the minerals and vitamins in these whole grains more accessible to the body and degrades most of the phytic acid, making the bread easier to digest.",
    "heirloom_faq_4_q": "Can I use 100% Einkorn for this style?",
    "heirloom_faq_4_a": "Yes, but be prepared for a very different experience. Einkorn is the 'oldest' wheat and has very weak gluten. It produces a dense, yellow, and incredibly nutty loaf that almost feels like a cross between bread and cake. Many bakers prefer to blend it 50/50 with a stronger heritage wheat like Turkey Red.",
    "heirloom_faq_5_q": "Why do these breads cost more at the bakery?",
    "heirloom_faq_5_a": "Heirloom grains are much harder for farmers to grow—they have lower yields and can be toppled by wind (lodging). Because they aren't produced on an industrial scale, the milling and transport are also more expensive. You are paying for the biodiversity, soil health, and the artisan skill required to bake with them.",

    # Babka
    "babka_intro": "Popular in Jewish and artisan bakeries, often sliced as a rich dessert or sweet snack.",
    "babka_history": "Babka is a sweet, braided bread that originated in the Jewish communities of Poland and Ukraine in the early 19th century. The name is diminutive of 'baba', meaning 'grandmother', referring to the wide, tall, fluted shape of traditional cakes common in the region (which looked like a grandmother's pleated skirt). In its original form, it was made with leftover challah dough and filled with jam or cinnamon. It wasn't until the mid-20th century, specifically in the Jewish bakeries of New York, that the chocolate-filled version (popularized by commercial cocoa) became the iconic standard we recognize today.",
    "babka_sig_1": "A cornerstone of Ashkenazi Jewish bakeries and Shabbat traditions",
    "babka_sig_2": "Symbolizes the 'grandmotherly' warmth and culinary heritage of Eastern Europe",
    "babka_sig_3": "Gained massive global pop-culture fame via the 1994 Seinfeld episode 'The Dinner Party'",
    "babka_sig_4": "Represents the marriage of lean bread techniques (braiding) with rich pastry enrichment",
    "babka_sig_5": "An icon of the New York City deli and bakery scene",
    "babka_consum_1": "Traditionally served on Shabbat or Jewish holidays as a sweet treat",
    "babka_consum_2": "Now a daily staple in 'Artisan' urban bakeries, sold as full loaves or thick slices",
    "babka_consum_3": "Commonly eaten as a mid-morning snack or afternoon tea with coffee",
    "babka_consum_4": "The 'End Slices' are often coveted for their high concentration of crispy topping",
    "babka_consum_5": "Used as the base for a decadent 'Babka French Toast' in modern brunch spots",
    "babka_evo_1": "1800s: Polish/Russian 'Baba' cakes are large, light, and mostly fruit-based",
    "babka_evo_2": "1900s: Jewish immigrants bring the recipe to America, simplifying it into a loaf form",
    "babka_evo_3": "1950s: Commercial chocolate and cinnamon become widely available, replacing jam fillings",
    "babka_evo_4": "2013-2015: Breads Bakery in NYC starts the 'Babka Renaissance', emphasizing high butter and chocolate %",
    "babka_evo_5": "Present: Flavors expand to include pistachio, halva, and savory variants like pesto",
    "babka_evo_6": "Future: Integration of whole grains into the enriched base for a more nutritious dessert bread",
    "babka_ritual_1": "The Pull: peeling back the moist layers to reveal the dark filling swirls",
    "babka_ritual_2": "The 'Stretch and Fold': the hypnotic process of layering dough and chocolate",
    "babka_ritual_3": "Applying the Syrup: brushing hot sugar syrup over the fresh-baked bread to lock in moisture",
    "babka_ritual_4": "The 'Krantz' Twist: the specific Israeli method of splitting the roll lengthwise and twisting for maximum visible layers",
    "babka_ritual_5": "The Shabbat Gift: bringing a wrapped babka as a thank-you to a dinner host",
    "babka_flavor_1": "Rich, eggy, and buttery bread base",
    "babka_flavor_2": "Deep cocoa or aromatic cinnamon heat",
    "babka_flavor_3": "Toasted hazelnut or walnut notes (if included in the filling)",
    "babka_flavor_4": "Sweet sugar-syrup finish with a hint of salt",
    "babka_flavor_5": "Mild yeasty undertones",
    "babka_aroma_1": "Intensity of dark chocolate or warm cinnamon",
    "babka_aroma_2": "Freshly baked brioche (butter-forward)",
    "babka_aroma_3": "Caramelized sugar",
    "babka_aroma_4": "Toasted nuts",
    "babka_aroma_5": "Warm yeast and vanilla",
    "babka_texture_1": "The 'Swirl': alternating layers of soft, pillowy dough and dense, fudgy filling",
    "babka_texture_2": "Moist and Tacky: the sugar syrup glaze creates a sticky, tender exterior",
    "babka_texture_3": "Streusel Crunch: crumbly bits on top provide a textural contrast to the soft interior",
    "babka_texture_4": "Silky Crumb: highly enriched dough that shreds easily into layers",
    "babka_texture_5": "Dense but not heavy: it should feel 'rich' but still maintain some bread-like structure",
    "babka_pair_1": "Coffee: A strong black Pour-over or a creamy Cappuccino",
    "babka_pair_2": "Tea: Earl Grey or Russian Caravan (smoky tea)",
    "babka_pair_3": "Spreads: Tahini drizzle or salted cultured butter",
    "babka_pair_4": "Fruit: Fresh raspberries or tart apricot jam",
    "babka_pair_5": "Dessert: A scoop of vanilla bean gelato or high-fat Greek yogurt",
    "babka_fe_1": "Fresh (0-6 hours): Peak softness; best for enjoying the feathery dough",
    "babka_fe_2": "Day 2: The filling moistens the surrounding dough even further; the flavors meld",
    "babka_fe_3": "Day 3: Excellent for dipping in milk or coffee",
    "babka_fe_4": "Day 5: Best transformed into French Toast or Bread Pudding",
    "babka_fe_5": "Freezing: Slices freeze well; toast directly from frozen for a 'Babka snack'",
    "babka_foundations_1": "Usually straight dough; some formulas use preferments.",
    "babka_foundations_2": "Hydration: 60-68%",
    "babka_di_1": "High enrichment (butter/yolks/sugar) creates a tender crumb and deep golden color",
    "babka_di_2": "Cold Fermentation (overnight) is MANDATORY for handling; the high fat makes warm dough too sticky to braid",
    "babka_di_3": "Moderate hydration (60-65%) balances the moisture from the filling to prevent a 'soggy' bake",
    "babka_di_4": "Use of Bread Flour (High Protein) is vital to support the heavy weight of the chocolate filling",
    "babka_di_5": "The dough must be stretched extremely thin (1-2mm) before filling to create the maximum number of swirls",
    "babka_bi_1": "Baked in tall loaf pans to support the heavy, twisted structure and encourage vertical lift",
    "babka_bi_2": "Lower oven temperature (170-185°C) prevents the sugar-heavy dough from burning before the center is done",
    "babka_bi_3": "Immediately brushing with simple syrup after baking creates the signature moist, tacky skin",
    "babka_bi_4": "Streusel (crumb) topping is often added to protect the exposed chocolate from drying in the oven",
    "babka_bi_5": "Must be cooled in the pan for 10-15 mins to allow the molten chocolate filling to set slightly",
    "babka_rv_1": "Polish Baba - The ancestor; often a light, tall, ring-shaped yeast cake with fruit",
    "babka_rv_2": "New York Jewish Babka - Famous for the thick, fudge-like chocolate swirl",
    "babka_rv_3": "Israeli 'Krantz' Cake - High-butter version split lengthwise to show exposed layers",
    "babka_rv_4": "Russian Paska - Variations using similar enriched dough for Easter celebrations",
    "babka_rv_5": "Contemporary Artisan Babka - Using sourdough starters and savory/creative fillings",
    "babka_cs_1": "Humid Summer: The chocolate filling can melt and bleed during shaping; work in small batches",
    "babka_cs_2": "Arid/Dry Environment: The dough will 'skin' fast; keep covered at all times during the rest",
    "babka_cs_3": "Cold Winter: The dough will take double the time to proof; use a warm proofing box at 26°C",
    "babka_cs_4": "High Altitude: Reduce sugar in the dough slightly to prevent the structure from collapsing",
    "babka_sc_1": "vs. Cinnamon Rolls: Babka is braided/twisted into a loaf vs being spiral-cut into individual buns",
    "babka_sc_2": "vs. Brioche: Babka uses a similar dough but focuses on the heavy-filling-to-dough ratio",
    "babka_sc_3": "vs. Challah: Challah is traditionally lean (no dairy) and braided, while Babka is rich and filled",
    "babka_sc_4": "vs. Panettone: Babka is much smaller and focuses on the 'swirl' vs Panettone's vertical aeration",
    "babka_ps_1": "Critical: Dough Thickness - if the dough is too thick during rolling, you'll have a bready center with no swirl",
    "babka_ps_2": "Highly sensitive: Filling Moisture - if the chocolate mix is too oily, the layers will separate during baking",
    "babka_ps_3": "Syrup Saturation: Too much syrup makes the loaf soggy; too little makes it dry out in 24 hours",
    "babka_ps_4": "Proofing: Enriched dough proves slowly; under-proofing leads to a split, 'burst' top",
    "babka_ps_5": "Chilling: Trying to shape an un-chilled babka dough is the #1 cause of failed 'swirls'",
    "babka_risk_1": "The 'Flying' Crust: Layers separating during baking due to excessive filling or under-proofing",
    "babka_risk_2": "The Soggy Bottom: Simple syrup pooling at the base of the loaf pan",
    "babka_risk_3": "Dry Crumb: Oven temperature was too high, or bake time was too long",
    "babka_risk_4": "Bloody Chocolate: Dark filling leaking out of the braid and burning on the pan",
    "babka_risk_5": "The Brick: Dough was too cold during final proof and never gained enough volume",
    "babka_note_1": "Always chill the dough for at least 6 hours before rolling for a cleaner 'cut'",
    "babka_note_2": "Add a pinch of salt to your chocolate filling to elevate the cocoa notes",
    "babka_note_3": "Use a serrated knife to cut the rolls for the 'Krantz' twist to avoid smashing the layers",
    "babka_note_4": "The syrup should be hot when applied to a hot loaf for maximum absorption",
    "babka_note_5": "Rotate the loaf pan halfway through the bake to ensure even browning of the sugars",
    "babka_faq_1_q": "Why is my Babka always dry inside?",
    "babka_faq_1_a": "Dry babka is usually caused by over-baking or not applying enough simple syrup right after the oven. The syrup is essential—it creates a moisture barrier that keeps the crumb tender. Also, ensure you aren't adding too much extra flour during the rolling and shaping phase.",
    "babka_faq_2_q": "What is the 'Krantz' style of shaping?",
    "babka_faq_2_a": "The Krantz (or Israeli) style involves rolling the dough with filling into a tight cylinder, then splitting that cylinder lengthwise to reveal the internal layers. Those two halves are then twisted over each other, creating a beautiful loaf where the chocolate is visible on top.",
    "babka_faq_3_q": "Do I really need to chill the dough overnight?",
    "babka_faq_3_a": "Yes. This high-fat enriched dough is very soft at room temperature. Chilling it makes the butter firm up, allowing you to stretch it into paper-thin layers and cut the braid without the whole thing turning into a sticky mess.",
    "babka_faq_4_q": "Can I make a savory Babka?",
    "babka_faq_4_a": "Absolutely! The same enriched dough works beautifully with savory fillings like pesto and parmesan, sun-dried tomato tapenade, or goat cheese and herbs. Just reduce the sugar in the dough slightly for these variants.",
    "babka_faq_5_q": "How long does a Babka stay fresh?",
    "babka_faq_5_a": "Because it's a rich, glazed bread, it stays fresh longer than a baguette, usually 3-4 days. For the best experience after day 1, we recommend warming a slice for 10 seconds in the microwave to melt the chocolate filling slightly.",

    # Milk Bread
    "milk_bread_intro": "Common in Japanese and Asian bakeries as a premium soft bread for toast and sandwiches.",
    "milk_bread_history": "Japanese Milk Bread (also known as Hokkaido Milk Bread) emerged as a distinct style in the mid-20th century in Japan. It was influenced by both Western sandwich bread and the traditional Japanese preference for soft, 'mochi-mochi' (chewy and elastic) textures. The defining technical innovation is the 'Tangzhong' (or Yudane) method—a Chinese/Japanese technique of pre-cooking a portion of the flour and liquid into a roux. This gelatinizes the starches, allowing the dough to absorb and retain significantly more moisture, creating the legendary cloud-like softness and legendary shreddability that has now taken the global culinary world by storm.",
    "milk_bread_sig_1": "The gold standard for softness and luxury in Asian bakery culture",
    "milk_bread_sig_2": "Represents the Japanese mastery of technical refinement applied to everyday foods",
    "milk_bread_sig_3": "Transformed white bread from a commodity into a high-end, giftable artisanal product",
    "milk_bread_sig_4": "Symbolizes the 'Mochi-Mochi' texture preference highly valued in Japanese cuisine",
    "milk_bread_sig_5": "A viral global sensation, frequently featured in 'food porn' for its extreme shreddability",
    "milk_bread_consum_1": "Commonly enjoyed as thick-cut 'Honey Toast' in Japanese cafes",
    "milk_bread_consum_2": "The mandatory base for the 'Tamago Sando' (Japanese egg salad sandwich)",
    "milk_bread_consum_3": "Often baked as decorative shaped rolls (animals, braids, or swirls)",
    "milk_bread_consum_4": "Served as a breakfast staple with butter, fruit preserves, or condensed milk",
    "milk_bread_consum_5": "Valued for its long shelf life; remains soft for 5-7 days without preservatives",
    "milk_bread_evo_1": "1940s: Post-WWII Japan adopts wheat-based breads due to food shortages and Western influence",
    "milk_bread_evo_2": "1980s: Hokkaido dairy products are combined with bread formulas to create extra-rich milk bread",
    "milk_bread_evo_3": "1990s: Yvonne Chen's book 'The 65°C Bread Doctor' popularizes the Tangzhong method across Asia",
    "milk_bread_evo_4": "2010s: Shokupan specialty shops (like Nogami) become cult destinations in Japan",
    "milk_bread_evo_5": "Present: Global adoption by artisan bakers using it for everything from burger buns to cinnamon rolls",
    "milk_bread_ritual_1": "The 'Pull-Apart' Test: slowly shredding the warm bread to see the long, feathery gluten strands",
    "milk_bread_ritual_2": "The Tangzhong Whisk: the careful cooking of the flour roux to exactly 65°C (149°F)",
    "milk_bread_ritual_3": "Thick Slicing: traditionally cutting slices 1.5 to 2 inches thick for restaurant-style toast",
    "milk_bread_ritual_4": "Hokkaido Branding: using high-fat dairy from the Hokkaido region for the Ultimate version",
    "milk_bread_ritual_5": "The 'Cloud' Squeeze: the tactile ritual of compressing the bread to feel its extreme rebound",
    "milk_bread_flavor_1": "Deeply milky and creamy (reminiscent of sweet butter and cream)",
    "milk_bread_flavor_2": "Mildly sweet with a clean, toasted wheat finish",
    "milk_bread_flavor_3": "Lactic and floral notes from the high dairy content",
    "milk_bread_flavor_4": "Subtle vanilla or honey-like undertones (depending on enrichment)",
    "milk_bread_flavor_5": "Zero acidity; focus is on pure, sweet fermentative clarity",
    "milk_bread_aroma_1": "Intense warm milk and sweet cream",
    "milk_bread_aroma_2": "Freshly baked pound cake or brioche",
    "milk_bread_aroma_3": "Clean, floral wheat notes",
    "milk_bread_aroma_4": "Sweet yeast and honey",
    "milk_bread_aroma_5": "Mild toasted butter",
    "milk_bread_texture_1": "The 'Cloud' Crumb: feathery, ultra-fine, and incredibly soft",
    "milk_bread_texture_2": "Extreme Shreddability: separates into long, thin sheets due to the Tangzhong-developed gluten",
    "milk_bread_texture_3": "Mochi-Mochi: a pleasant, elastic chewiness that isn't tough",
    "milk_bread_texture_4": "Moist and 'Wet' Mouthfeel: stays hydrating on the tongue unlike dry industrial bread",
    "milk_bread_texture_5": "Parchment-Thin Crust: a very delicate, soft skin that is as tender as the crumb",
    "milk_bread_pair_1": "Sweet: Condensed milk drizzle, strawberry jam, or chocolate-hazelnut spread",
    "milk_bread_pair_2": "Savory: Japanese egg salad (Tamago), Katsu (fried pork cutlets), or soft-scrambled eggs",
    "milk_bread_pair_3": "Drink: Matcha latte, Royal Milk Tea, or high-quality black coffee",
    "milk_bread_pair_4": "Meal: Fruit Sandwiches (Fruit Sando) with whipped cream and fresh peaches",
    "milk_bread_pair_5": "Butter: Lightly salted cultured butter, whipped to room temperature",
    "milk_bread_fe_1": "Fresh (0-4 hours): At its most feathery; melts in the mouth almost like cotton candy",
    "milk_bread_fe_2": "Day 2-3: Peak flavor; the milky notes intensify while the crumb remains perfectly soft",
    "milk_bread_fe_3": "Day 5: Still surprisingly moist thanks to the Tangzhong moisture retention",
    "milk_bread_fe_4": "Stale: Best used for legendary French Toast (it absorbs custard like a sponge)",
    "milk_bread_fe_5": "Freezing: Freezes perfectly; thaw at room temperature in the bag to preserve moisture",
    "milk_bread_foundations_1": "Straight dough with tangzhong; some formulas use sponge.",
    "milk_bread_foundations_2": "Hydration: 68-75%",
    "milk_bread_di_1": "Tangzhong (Flour/Liquid Roux) pre-gelatinizes starch, allowing the dough to hold 10-15% more water",
    "milk_bread_di_2": "High enrichment (Heavy Cream, Milk, Butter, Honey) provides the luxurious flavor and aroma",
    "milk_bread_di_3": "Intensive mixing (to full windowpane) is mandatory to achieve the signature 'shreddable' strands",
    "milk_bread_di_4": "Lower internal temperature during mixing is key to prevent the fats from melting prematurely",
    "milk_bread_di_5": "Slow bulk fermentation allows the enzymes in the milk and honey to develop complex sweetness",
    "milk_bread_bi_1": "Baked at lower temperatures (170-180°C) to maintain the paper-thin, soft, blonde crust",
    "milk_bread_bi_2": "High humidity in the early bake prevents the crust from setting, allowing for 'exploding' oven spring",
    "milk_bread_bi_3": "Uniform loaf shape (Pullman or Open-Top) ensures even heat distribution to the center",
    "milk_bread_bi_4": "Milk wash or light egg wash provides the iconic satin-gloss finish",
    "milk_bread_bi_5": "Cooling slowly in a draft-free area ensures the steam stays inside, tenderizing the crust further",
    "milk_bread_rv_1": "Hokkaido Milk Bread - The rich benchmark using Hokkaido milk and heavy cream",
    "milk_bread_rv_2": "Honeydew/Melon Pan - Milk bread dough topped with a cookie crust",
    "milk_bread_rv_3": "Sausage Bun - The classic Asian bakery staple using milk bread as the vessel",
    "milk_bread_rv_4": "Ube/Taro Swirl - Variant using purple yam or taro paste for color and flavor",
    "milk_bread_rv_5": "Shokupan (Pullman) - The square, lid-baked version designed for uniform sandwiches",
    "milk_bread_cs_1": "Extreme Humidity: The bread will absorb air moisture and become 'heavy'; bake 3 mins longer",
    "milk_bread_cs_2": "Arid/Dry Environment: The crust will try to go crisp; brush with milk IMMEDIATELY after baking",
    "milk_bread_cs_3": "Winter/Cold: Use warm milk (35°C) for the dough to ensure the yeast can lift the heavy fats",
    "milk_bread_cs_4": "Professional Bakery: Retard shaped loaves at 5°C to allow for easier scheduling and flavor depth",
    "milk_bread_sc_1": "vs. Brioche: Milk bread uses less fat and Tangzhong; it's more elastic and moist/less cakey",
    "milk_bread_sc_2": "vs. American Sandwich Bread: Milk bread is much richer, softer, and has far superior shelf life",
    "milk_bread_sc_3": "vs. Pain de Mie: Milk bread focuses on 'shred' and 'chew' (mochi) vs. Pain de Mie's short, tender bite",
    "milk_bread_sc_4": "vs. Focaccia: Opposite ends; Milk bread is structured and soft vs. Focaccia's open and oil-fried",
    "milk_bread_ps_1": "Critical: Tangzhong Prep - if not cooked to 65°C, the starch won't gelatinize correctly",
    "milk_bread_ps_2": "Highly sensitive: Kneading - without full windowpane, you will lose the 'shred' effect",
    "milk_bread_ps_3": "Dairy Fat %: Using skim milk instead of whole milk/cream drastically reduces the luxury feel",
    "milk_bread_ps_4": "Yeast Activity: High sugar content needs active yeast; sugar-tolerant yeast is recommended",
    "milk_bread_ps_5": "Proofing Height: If it doesn't reach the rim of the pan, the crumb won't have the right density",
    "milk_bread_risk_1": "The 'Cave-In': Sides collapsing after baking due to weak gluten structure or under-baking",
    "milk_bread_risk_2": "Dense Layer at Bottom: Not kneading enough or too much 'raw' flour used during shaping",
    "milk_bread_risk_3": "Yeasty Smell: Over-proofing in a hot environment (above 30°C)",
    "milk_bread_risk_4": "Dry Crumb: Skipping the Tangzhong or using too little fat/liquid",
    "milk_bread_risk_5": "Burnt Top: Sugar content in the dough causes fast browning; tent with foil if needed",
    "milk_bread_note_1": "Always make the Tangzhong first and let it cool completely (or refrigerate) before mixing",
    "milk_bread_note_2": "Use high-protein Bread Flour (12.5%+) to handle the high liquid and fat enrichment",
    "milk_bread_note_3": "Try 'Yudane' (flour scalded with boiling water) for a slightly chewier, more traditional Japanese feel",
    "milk_bread_note_4": "Don't slice it while hot—the steam will escape and the crumb will become gummy",
    "milk_bread_note_5": "The 'Spiral' shaping method (rolling dough into cylinders) is what creates the shreddable layers",
    "milk_bread_faq_1_q": "What is Tangzhong and why is it used?",
    "milk_bread_faq_1_a": "Tangzhong is a roux made by cooking a small portion of the flour and liquid (usually 1:5 ratio) until it becomes a paste. This pre-gelatinizes the starch, allowing the dough to hold more moisture without becoming sticky. The result is bread that is significantly softer and stays fresh for much longer.",
    "milk_bread_faq_2_q": "What is the secret to getting the 'shreddable' crumb?",
    "milk_bread_faq_2_a": "The secret is extreme gluten development. You must knead the dough until it passes the 'windowpane test' (you can stretch a small piece until it's translucent without breaking). This strong, elastic network, combined with the rolling shaping method, creates the feathery strands.",
    "milk_bread_faq_3_q": "Can I use regular All-Purpose flour for Milk Bread?",
    "milk_bread_faq_3_a": "You can, but Bread Flour (high protein) is highly recommended. The high fat and liquid content require a strong gluten structure to rise properly. All-Purpose flour may result in a loaf that is too soft and prone to collapsing.",
    "milk_bread_faq_4_q": "Why did my milk bread collapse on the sides after baking?",
    "milk_bread_faq_4_a": "This is often called 'cave-in' and usually happens if the internal structure wasn't strong enough (under-kneaded) or if the bread was under-baked. Ensure the internal temperature reaches 90°C (195°F) before removing it from the oven.",
    "milk_bread_faq_5_q": "Does it really need heavy cream?",
    "milk_bread_faq_5_a": "While you can use only milk, heavy cream adds a level of luxury and 'milky' aroma that is characteristic of premium Japanese bakeries. It provides both fat and proteins that result in a superior mouthfeel.",
}

data.update(new_keys)

# Sort keys alphabetically
sorted_data = dict(sorted(data.items()))

with open(file_path, 'w', encoding='utf-8') as f:
    json.dump(sorted_data, f, indent=2, ensure_ascii=False)

print(f"Added {len(new_keys)} keys to {file_path}")
