import type { GuidanceItem } from '@/types';

export const GUIDANCE_ITEMS: GuidanceItem[] = [
  {
    id: 'calculator-workflow-tip',
    scope: 'calculator',
    route: 'calculator',
    trigger: 'first-visit',
    variant: 'orientation',
    title: 'Choose the workflow that matches how much guidance you want.',
    body: 'Guided is the safest default, Wizard explains the flow step by step, and Advanced is best when you already know which variables you want to control directly.',
    priority: 90,
    dismissible: true,
    cardId: 'calculator-workflow',
    placement: 'bottom',
    titleKey: 'guidance.calculator.workflow.title',
    bodyKey: 'guidance.calculator.workflow.body',
  },
  {
    id: 'calculator-inputs-tip',
    scope: 'calculator',
    route: 'calculator',
    trigger: 'manual',
    variant: 'hint',
    title: 'Lock the big inputs first, then fine-tune percentages.',
    body: 'Style, quantity, and environment usually matter more than micro-adjusting ingredients too early. Stabilize those first so the formula is easier to trust.',
    priority: 80,
    dismissible: true,
    cardId: 'calculator-inputs',
    placement: 'left',
    titleKey: 'guidance.calculator.inputs.title',
    bodyKey: 'guidance.calculator.inputs.body',
  },
  {
    id: 'calculator-results-tip',
    scope: 'calculator',
    route: 'calculator',
    trigger: 'after-result',
    variant: 'hint',
    title: 'Treat this output as a working plan, not just a list of numbers.',
    body: 'The biggest improvement comes after you log the bake in My Lab, rate the result, and compare what changed from one run to the next.',
    ctaLabel: 'Open My Lab',
    priority: 70,
    dismissible: true,
    cardId: 'calculator-results',
    placement: 'left',
    titleKey: 'guidance.calculator.results.title',
    bodyKey: 'guidance.calculator.results.body',
    ctaKey: 'guidance.calculator.results.cta',
  },
  {
    id: 'mylab-overview-tip',
    scope: 'mylab',
    route: 'mylab',
    trigger: 'first-visit',
    variant: 'orientation',
    title: 'Use the overview to check momentum, not perfection.',
    body: 'What matters here is whether you are keeping the feedback loop active enough to spot patterns across bakes, levain care, and notes.',
    priority: 85,
    dismissible: true,
    cardId: 'mylab-overview',
    placement: 'bottom',
    titleKey: 'guidance.mylab.overview.title',
    bodyKey: 'guidance.mylab.overview.body',
  },
  {
    id: 'mylab-actions-tip',
    scope: 'mylab',
    route: 'mylab',
    trigger: 'first-visit',
    variant: 'hint',
    title: 'These cards should tell you the next best move, not become another backlog.',
    body: 'Use them to pick one useful action now, then come back later instead of trying to clean up the whole lab in one session.',
    priority: 78,
    dismissible: true,
    cardId: 'mylab-actions',
    placement: 'bottom',
    titleKey: 'guidance.mylab.actions.title',
    bodyKey: 'guidance.mylab.actions.body',
  },
  {
    id: 'mylab-recent-tip',
    scope: 'mylab',
    route: 'mylab',
    trigger: 'manual',
    variant: 'hint',
    title: 'Recent activity becomes useful once you compare runs with intent.',
    body: 'Look for one changed variable, one quality signal, and one next adjustment instead of reading the timeline like a passive history feed.',
    priority: 72,
    dismissible: true,
    cardId: 'mylab-recent',
    placement: 'left',
    titleKey: 'guidance.mylab.recent.title',
    bodyKey: 'guidance.mylab.recent.body',
  },
  {
    id: 'mylab-timeline-tip',
    scope: 'mylab',
    route: 'mylab',
    trigger: 'manual',
    variant: 'reference',
    title: 'Timeline works best when you keep the cadence fresh.',
    body: 'It helps you see rhythm and timing decisions over time, especially after a few consecutive sessions.',
    priority: 68,
    dismissible: true,
    cardId: 'mylab-timeline',
    placement: 'left',
    titleKey: 'guidance.mylab.timeline.title',
    bodyKey: 'guidance.mylab.timeline.body',
  },
  {
    id: 'mylab-bakes-tip',
    scope: 'mylab',
    route: 'mylab',
    trigger: 'manual',
    variant: 'reference',
    title: 'Bakes are the core record of what you planned, what happened, and what to change next.',
    body: 'If you only save formulas and skip notes or ratings, you lose the main learning value of the lab.',
    priority: 66,
    dismissible: true,
    cardId: 'mylab-bakes',
    placement: 'left',
    titleKey: 'guidance.mylab.bakes.title',
    bodyKey: 'guidance.mylab.bakes.body',
  },
  {
    id: 'mylab-levain-tip',
    scope: 'mylab',
    route: 'mylab',
    trigger: 'manual',
    variant: 'reference',
    title: 'Levain tracking matters when routine and timing affect the bake outcome.',
    body: 'Keep one starter predictable before adding more complexity, and log feedings close to when they happen.',
    priority: 64,
    dismissible: true,
    cardId: 'mylab-levain',
    placement: 'left',
    titleKey: 'guidance.mylab.levain.title',
    bodyKey: 'guidance.mylab.levain.body',
  },
  {
    id: 'mylab-consistency-tip',
    scope: 'mylab',
    route: 'mylab',
    trigger: 'manual',
    variant: 'reference',
    title: 'Consistency improves faster when you change one meaningful variable at a time.',
    body: 'Use comparisons and notes to isolate the factor you are testing instead of changing everything between sessions.',
    priority: 62,
    dismissible: true,
    cardId: 'mylab-consistency',
    placement: 'left',
    titleKey: 'guidance.mylab.consistency.title',
    bodyKey: 'guidance.mylab.consistency.body',
  },
  {
    id: 'levain-empty-tip',
    scope: 'levain',
    route: 'mylab/levain',
    trigger: 'empty-state',
    variant: 'orientation',
    title: 'Start with one simple starter and one consistent rhythm.',
    body: 'The goal is to build a reliable routine first, then expand only after the signals make sense to you.',
    ctaLabel: 'Create first levain',
    priority: 80,
    dismissible: true,
    cardId: 'levain-empty',
    placement: 'bottom',
    titleKey: 'guidance.levain.empty.title',
    bodyKey: 'guidance.levain.empty.body',
    ctaKey: 'guidance.levain.empty.cta',
  },
  {
    id: 'levain-card-tip',
    scope: 'levain',
    route: 'mylab/levain',
    trigger: 'manual',
    variant: 'hint',
    title: 'Use each starter card as a quick status check before opening the detail page.',
    body: 'What matters most here is last feeding, current status, and whether the starter still matches the routine you expect.',
    priority: 60,
    dismissible: true,
    cardId: 'levain-card',
    placement: 'left',
    titleKey: 'guidance.levain.card.title',
    bodyKey: 'guidance.levain.card.body',
  },
  {
    id: 'help-task-hub',
    scope: 'help',
    route: 'help',
    trigger: 'manual',
    variant: 'reference',
    title: 'Use task paths when you want the shortest route to an outcome.',
    body: 'This page should help you choose the next workflow quickly instead of forcing you to browse the product section by section.',
    priority: 55,
    dismissible: true,
    cardId: 'help-task-hub',
    placement: 'bottom',
    titleKey: 'guidance.help.hub.title',
    bodyKey: 'guidance.help.hub.body',
  },
  {
    id: 'help-task-first-formula',
    scope: 'help',
    route: 'help',
    trigger: 'manual',
    variant: 'reference',
    title: 'Best when you want a reliable starting dough without overthinking the setup.',
    body: 'Use this path if the main job is getting to a usable first formula quickly.',
    priority: 54,
    dismissible: true,
    cardId: 'help-task-first-formula',
    placement: 'left',
    titleKey: 'guidance.help.task_formula_tip.title',
    bodyKey: 'guidance.help.task_formula_tip.body',
  },
  {
    id: 'help-task-save-bake',
    scope: 'help',
    route: 'help',
    trigger: 'manual',
    variant: 'reference',
    title: 'Best when you already have a formula and want to preserve context around the result.',
    body: 'This path matters once you are ready to connect numbers, notes, and outcome in one place.',
    priority: 53,
    dismissible: true,
    cardId: 'help-task-save-bake',
    placement: 'left',
    titleKey: 'guidance.help.task_save_tip.title',
    bodyKey: 'guidance.help.task_save_tip.body',
  },
  {
    id: 'help-task-levain',
    scope: 'help',
    route: 'help',
    trigger: 'manual',
    variant: 'reference',
    title: 'Best when you want to use levain without turning setup into a side project.',
    body: 'Start here if your main concern is keeping one starter understandable and repeatable.',
    priority: 52,
    dismissible: true,
    cardId: 'help-task-levain',
    placement: 'left',
    titleKey: 'guidance.help.task_levain_tip.title',
    bodyKey: 'guidance.help.task_levain_tip.body',
  },
  {
    id: 'help-task-compare-results',
    scope: 'help',
    route: 'help',
    trigger: 'manual',
    variant: 'reference',
    title: 'Best when you already have a few runs and need to see what is actually improving.',
    body: 'Use this path to move from isolated sessions toward comparisons and trends.',
    priority: 51,
    dismissible: true,
    cardId: 'help-task-compare-results',
    placement: 'left',
    titleKey: 'guidance.help.task_compare_tip.title',
    bodyKey: 'guidance.help.task_compare_tip.body',
  },
  {
    id: 'help-task-workflow-choice',
    scope: 'help',
    route: 'help',
    trigger: 'manual',
    variant: 'reference',
    title: 'Best when you are unsure which calculator mode fits your level of confidence.',
    body: 'Use it to decide whether you want safety rails, step-by-step explanation, or direct control.',
    priority: 50,
    dismissible: true,
    cardId: 'help-task-workflow-choice',
    placement: 'left',
    titleKey: 'guidance.help.task_workflow_tip.title',
    bodyKey: 'guidance.help.task_workflow_tip.body',
  },
  {
    id: 'profile-preferences-tip',
    scope: 'profile',
    route: 'profile',
    trigger: 'manual',
    variant: 'reference',
    title: 'Use preferences to re-enable tips and keep the app aligned with how you bake now.',
    body: 'This is now the manual entry point for guidance, not a long onboarding flow.',
    ctaLabel: 'View tips again',
    priority: 58,
    dismissible: true,
    cardId: 'profile-preferences',
    placement: 'bottom',
    titleKey: 'guidance.profile.preferences.title',
    bodyKey: 'guidance.profile.preferences.body',
    ctaKey: 'guidance.profile.preferences.cta',
  },
  {
    id: 'profile-resources-tip',
    scope: 'profile',
    route: 'profile',
    trigger: 'manual',
    variant: 'reference',
    title: 'Use resources when you need supporting knowledge, not when you need the next action.',
    body: 'The help hub should answer workflow questions first, and this card should support deeper reading second.',
    priority: 48,
    dismissible: true,
    cardId: 'profile-resources',
    placement: 'left',
    titleKey: 'guidance.profile.resources.title',
    bodyKey: 'guidance.profile.resources.body',
  },
  {
    id: 'settings-preferences-tip',
    scope: 'settings',
    route: 'profile',
    trigger: 'manual',
    variant: 'reference',
    title: 'Settings should shape defaults and behavior, not teach the whole product.',
    body: 'Use this area to tune language, units, and account behavior after you already know the workflow you want.',
    priority: 47,
    dismissible: true,
    cardId: 'profile-settings',
    placement: 'bottom',
    titleKey: 'guidance.settings.preferences.title',
    bodyKey: 'guidance.settings.preferences.body',
  },
];

export const GUIDANCE_ITEMS_BY_ID = GUIDANCE_ITEMS.reduce<Record<string, GuidanceItem>>((acc, item) => {
  acc[item.id] = item;
  return acc;
}, {});
