import React, { useMemo } from 'react';
import { DoughConfig } from '@/types';
import { Droplets, Thermometer, ToggleLeft, ToggleRight } from 'lucide-react';
import AccordionSection from '@/components/calculator/AccordionSection';
import { AMBIENT_TEMP_CELSIUS_MAP } from '@/constants';
import { calculateWaterTempDDT } from '@/helpers';
import { InfoTooltip } from '@/components/ui/InfoTooltip';
import { useTranslation } from '@/i18n';

interface WaterTempHelperProps {
    id?: string;
    config: DoughConfig;
    onConfigChange: (newConfig: Partial<DoughConfig>) => void;
    calculatorMode: 'wizard' | 'basic' | 'advanced';
}

const DEFAULT_DDT = 25;

const WaterTempHelper: React.FC<WaterTempHelperProps> = ({
    id,
    config,
    onConfigChange,
    calculatorMode,
}) => {
    const { t } = useTranslation();
    const isAdvanced = calculatorMode === 'advanced';
    const roomTempC = AMBIENT_TEMP_CELSIUS_MAP[config.ambientTemperature];
    const flourTempC = config.flourTemperatureC ?? roomTempC;
    const targetDDT = config.targetDDT ?? DEFAULT_DDT;
    const useFriction = config.useFrictionFactor ?? false;
    const flourIsSameAsRoom = config.flourTemperatureC === undefined || config.flourTemperatureC === null;

    const waterTempC = useMemo(() => {
        return calculateWaterTempDDT(targetDDT, roomTempC, flourTempC, useFriction);
    }, [targetDDT, roomTempC, flourTempC, useFriction]);

    // Temperature quality indicator
    const tempQuality = useMemo(() => {
        if (waterTempC < 2) return { label: t('calculator.water_temp_too_cold', { defaultValue: 'Ice water needed!' }), color: 'text-blue-600', bg: 'bg-blue-50', border: 'border-blue-200' };
        if (waterTempC < 10) return { label: t('calculator.water_temp_cold', { defaultValue: 'Very cold water' }), color: 'text-cyan-600', bg: 'bg-cyan-50', border: 'border-cyan-200' };
        if (waterTempC <= 25) return { label: t('calculator.water_temp_ideal', { defaultValue: 'Comfortable range' }), color: 'text-emerald-600', bg: 'bg-emerald-50', border: 'border-emerald-200' };
        if (waterTempC <= 38) return { label: t('calculator.water_temp_warm', { defaultValue: 'Warm water' }), color: 'text-amber-600', bg: 'bg-amber-50', border: 'border-amber-200' };
        return { label: t('calculator.water_temp_hot', { defaultValue: 'Hot — be careful!' }), color: 'text-red-600', bg: 'bg-red-50', border: 'border-red-200' };
    }, [waterTempC, t]);

    const frictionTooltip = t('calculator.friction_tooltip', {
        defaultValue: `<strong>${t('calculator:friction_factor')}</strong> compensates for heat generated by your mixer during kneading. When enabled, the formula subtracts ~3°C from the recommended water temperature.<br/><br/>
    <strong>${t('calculator:enable_if')}</strong> You use a stand mixer or spiral mixer for >5 minutes.<br/>
    <strong>${t('calculator:disable_if')}</strong> ${t('calculator:you_knead_by_hand_or_use_a_brief_machine_mix')} (<3 min).<br/><br/>
    <em>Formula: Standard = (DDT × 3) − Room − Flour.<br/>With friction = ((DDT − 1) × 3) − Room − Flour.</em>`,
    });

    const ddtTooltip = t('calculator.ddt_tooltip', {
        defaultValue: `<strong>${t('calculator:desired_dough_temperature_ddt')}</strong> is the ideal internal temperature of your freshly mixed dough. For most breads and pizzas, <strong>24–26°C</strong> is optimal. Lower DDT (22–23°C) slows fermentation for longer cold proofs. Higher DDT (27–28°C) accelerates fermentation for quick bakes.`,
    });

    return (
        <AccordionSection
            id={id}
            index={6}
            accentColor="blue"
            title={t('calculator.water_temp_helper', { defaultValue: 'Water Temperature' })}
            description={t('calculator.water_temp_helper_desc', { defaultValue: 'DDT-based recommendation' })}
            icon={<Droplets />}
        >
            <div className="space-y-5 animate-slide-up">
                {/* Main Result Card */}
                <div className={`relative overflow-hidden rounded-2xl ${tempQuality.bg} ${tempQuality.border} border p-5`}>
                    {/* Background decoration */}
                    <div className="absolute -top-4 -right-4 w-24 h-24 rounded-full bg-white/20 blur-xl" />
                    <div className="absolute -bottom-6 -left-6 w-20 h-20 rounded-full bg-white/15 blur-lg" />

                    <div className="relative flex items-center gap-4">
                        {/* Temperature Display */}
                        <div className="flex-shrink-0 w-20 h-20 rounded-2xl bg-white/80 backdrop-blur-sm flex flex-col items-center justify-center shadow-sm border border-white/60">
                            <Droplets className={`w-5 h-5 ${tempQuality.color} mb-1`} />
                            <span className={`text-2xl font-black ${tempQuality.color} tabular-nums leading-none`}>
                                {waterTempC.toFixed(0)}°
                            </span>
                            <span className="text-[8px] font-bold uppercase tracking-widest text-slate-400 mt-0.5">{t('calculator:celsius')}</span>
                        </div>

                        {/* Info */}
                        <div className="flex-grow min-w-0">
                            <h4 className={`text-sm font-bold ${tempQuality.color} mb-1`}>
                                {t('calculator.recommended_water_temp', { defaultValue: 'Recommended Water Temp' })}
                            </h4>
                            <p className="text-[11px] text-slate-500 leading-relaxed mb-2">
                                {t('calculator.water_temp_explanation', {
                                    defaultValue: 'Use water at this temperature to achieve your desired dough temperature (DDT {{ddt}}°C).',
                                    ddt: targetDDT,
                                })}
                            </p>
                            <div className={`inline-flex items-center gap-1.5 px-2 py-1 rounded-full text-[9px] font-bold uppercase tracking-widest ${tempQuality.bg} ${tempQuality.color} ${tempQuality.border} border`}>
                                <Thermometer className="w-3 h-3" />
                                {tempQuality.label}
                            </div>
                        </div>
                    </div>

                    {/* Formula breakdown (subtle) */}
                    <div className="mt-4 pt-3 border-t border-white/40 flex flex-wrap items-center gap-x-4 gap-y-1 text-[10px] text-slate-500">
                        <span className="flex items-center gap-1">
                            🌡️ {t('calculator.room', { defaultValue: 'Room' })}: <strong className="text-slate-700">{roomTempC}°C</strong>
                        </span>
                        <span className="flex items-center gap-1">
                            🌾 {t('calculator.flour', { defaultValue: 'Flour' })}: <strong className="text-slate-700">{flourTempC}°C</strong>
                            {flourIsSameAsRoom && <span className="text-slate-400 italic">({t('calculator.same_as_room', { defaultValue: '= room' })})</span>}
                        </span>
                        <span className="flex items-center gap-1">
                            🎯 DDT: <strong className="text-slate-700">{targetDDT}°C</strong>
                        </span>
                        {useFriction && (
                            <span className="flex items-center gap-1 text-amber-600">
                                ⚙️ {t('calculator.friction_on', { defaultValue: 'Friction: -3°C' })}
                            </span>
                        )}
                    </div>
                </div>

                {/* Advanced Controls */}
                {isAdvanced && (
                    <div className="space-y-4 pt-2 border-t border-slate-100">
                        {/* DDT Target */}
                        <div>
                            <div className="flex items-center gap-2 mb-2">
                                <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#1B4332] block">
                                    {t('calculator.target_ddt', { defaultValue: 'Target Dough Temp (DDT)' })}
                                </label>
                                <InfoTooltip
                                    content={ddtTooltip}
                                    position="right"
                                    size="lg"
                                    variant="tutorial"
                                />
                            </div>
                            <div className="relative">
                                <input
                                    type="number"
                                    value={targetDDT}
                                    onChange={(e) => {
                                        const val = parseFloat(e.target.value);
                                        if (!isNaN(val) && val >= 18 && val <= 35) {
                                            onConfigChange({ targetDDT: val });
                                        }
                                    }}
                                    className="block w-full rounded-2xl border-slate-200 bg-slate-50 py-3 px-4 text-xl font-bold text-slate-800 focus:border-[#1B4332] focus:bg-white focus:ring-4 focus:ring-dlp-brand/5 transition-all outline-none min-h-[44px]"
                                    placeholder="25"
                                    min={18}
                                    max={35}
                                    step={0.5}
                                />
                                <div className="absolute inset-y-0 right-6 flex items-center pointer-events-none">
                                    <span className="text-sm font-bold text-slate-400">°C</span>
                                </div>
                            </div>
                        </div>

                        {/* Flour Temperature Toggle */}
                        <div>
                            <div className="flex items-center justify-between mb-2">
                                <div className="flex items-center gap-2">
                                    <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#1B4332]">
                                        {t('calculator.flour_temperature', { defaultValue: 'Flour Temperature' })}
                                    </label>
                                    <InfoTooltip
                                        content={t('calculator.flour_temp_tooltip', {
                                            defaultValue: 'Flour stored in a cold pantry or cellar may be significantly cooler than room temperature. If your flour is at a different temperature than the room, toggle this off and set the actual flour temperature for a more accurate water temp recommendation.',
                                        })}
                                        position="right"
                                        size="lg"
                                    />
                                </div>
                                {/* Same as Room Toggle */}
                                <button
                                    onClick={() => {
                                        if (flourIsSameAsRoom) {
                                            onConfigChange({ flourTemperatureC: roomTempC });
                                        } else {
                                            onConfigChange({ flourTemperatureC: undefined });
                                        }
                                    }}
                                    className={`flex items-center gap-2 px-3 py-2.5 rounded-full text-[9px] font-bold uppercase tracking-widest transition-all duration-300 border min-h-[44px]
                                        ${flourIsSameAsRoom
                                            ? 'bg-emerald-50 text-emerald-600 border-emerald-200'
                                            : 'bg-slate-50 text-slate-400 border-slate-200 hover:text-slate-600'
                                        }`}
                                >
                                    {flourIsSameAsRoom
                                        ? <ToggleRight className="w-4 h-4" />
                                        : <ToggleLeft className="w-4 h-4" />
                                    }
                                    {t('calculator.same_as_room', { defaultValue: '= Room' })}
                                </button>
                            </div>

                            {/* Custom Flour Temperature Input */}
                            {!flourIsSameAsRoom && (
                                <div className="relative animate-slide-up">
                                    <input
                                        type="number"
                                        value={flourTempC}
                                        onChange={(e) => {
                                            const val = parseFloat(e.target.value);
                                            if (!isNaN(val) && val >= 0 && val <= 40) {
                                                onConfigChange({ flourTemperatureC: val });
                                            }
                                        }}
                                        className="block w-full rounded-2xl border-slate-200 bg-slate-50 py-3 px-4 text-xl font-bold text-slate-800 focus:border-[#1B4332] focus:bg-white focus:ring-4 focus:ring-dlp-brand/5 transition-all outline-none min-h-[44px]"
                                        placeholder={`${roomTempC}`}
                                        min={0}
                                        max={40}
                                        step={1}
                                    />
                                    <div className="absolute inset-y-0 right-6 flex items-center pointer-events-none">
                                        <span className="text-sm font-bold text-slate-400">°C</span>
                                    </div>
                                </div>
                            )}
                        </div>

                        {/* Friction Factor Toggle */}
                        <div className="flex items-center justify-between p-3 rounded-2xl bg-slate-50 border border-slate-100">
                            <div className="flex items-center gap-2">
                                <label className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#1B4332]">
                                    {t('calculator.friction_factor', { defaultValue: 'Friction Factor' })}
                                </label>
                                <InfoTooltip
                                    content={frictionTooltip}
                                    position="top"
                                    size="lg"
                                    variant="tutorial"
                                />
                            </div>
                            <button
                                onClick={() => onConfigChange({ useFrictionFactor: !useFriction })}
                                className={`flex items-center gap-2 px-3 py-2.5 rounded-full text-[9px] font-bold uppercase tracking-widest transition-all duration-300 border min-h-[44px]
                                    ${useFriction
                                        ? 'bg-amber-50 text-amber-600 border-amber-200'
                                        : 'bg-slate-100 text-slate-400 border-slate-200 hover:text-slate-600'
                                    }`}
                            >
                                {useFriction
                                    ? <ToggleRight className="w-4 h-4" />
                                    : <ToggleLeft className="w-4 h-4" />
                                }
                                {useFriction
                                    ? t('calculator.enabled', { defaultValue: 'On' })
                                    : t('calculator.disabled', { defaultValue: 'Off' })
                                }
                            </button>
                        </div>
                    </div>
                )}
            </div>
        </AccordionSection>
    );
};

export default WaterTempHelper;