
import json

data = {
    "new_york_slice_v2_science_flour": "A alta proteína requer óleo/açúcar (amaciantes) para permitir a 'dobra' sem que a crosta rache como um biscoito. A densidade do glúten suporta o grande diâmetro de 18 polegadas.",
    "new_york_slice_v2_dd_hydration": "62-65% é o ponto ideal. Permite que a massa seja extensível o suficiente para o estiramento de 18 polegadas, mas fornece estrutura suficiente para segurar a dobra ('The Fold') sem cair.",
    "detroit_style_classic_science_flour": "A estrutura é suportada pelas paredes da forma de aço, então não precisamos de força de glúten extrema. A alta hidratação ajuda no miolo aberto tipo 'focaccia'.",
    "detroit_style_classic_dd_hydration": "70-75% é obrigatório. Isso é efetivamente uma focaccia assada com queijo. A água alta garante que o miolo grosso permaneça leve e aerado como uma esponja, não denso como um tijolo.",
    "chicago_deep_dish_science_flour": "Uma 'Massa Curta'. O alto teor de gordura reveste as proteínas, prevenindo longas cadeias de glúten. Isso cria uma quebra folhada, tipo biscoito, em vez de uma mastigável.",
    "chicago_deep_dish_dd_hydration": "50-55% mais alta gordura (15%+ Óleo de Milho/Manteiga). Isso NÃO é pão. É uma crosta de torta salgada. Hidratação alta desenvolveria glúten -> mastigável -> errado.",
    "sf_sourdough_science_flour": "A proteólise (ácido degradando glúten) é o inimigo. Precisamos de farinha muito forte para sobreviver à longa fermentação ácida sem colapsar.",
    "sf_sourdough_dd_hydration": "75%+ é padrão. A acidez do Levain tensiona a estrutura do glúten, permitindo que ele segure muita água sem virar sopa. A água é necessária para o miolo aberto.",
    "new_haven_apizza_science_flour": "Alta força é necessária para esticar muito fino sem rasgar, mas fermentação a frio prolongada relaxa o glúten (extensibilidade).",
    "new_haven_apizza_dd_hydration": "60-65% impulsiona o chamuscado. Precisa estar seco o suficiente para crocância rápida, mas úmido o suficiente para suportar a fermentação de 48h sem secar na geladeira.",
    "nyc_bagel_science_flour": "A farinha com maior proteína possível é usada. Como a hidratação é baixa (50%), o glúten é incrivelmente tenso, criando a textura mastigável 'exercício de mandíbula'.",
    "nyc_bagel_dd_hydration": "50-55% é rígida. Extremamente rígida. Essa tensão + fervura é o que restringe a expansão, criando a textura densa e mastigável. Se você hidratar a 65%, acabou de fazer um pãozinho redondo.",
    "grandma_style_v2_science_flour": "Não requer alta proteína. Uma farinha mais macia ajuda a esticar nos cantos da forma sem encolher de volta.",
    "grandma_style_v2_dd_hydration": "60-65% garante um fundo crocante (frito no óleo da forma) mas um miolo denso o suficiente para suportar as coberturas. Muito aerado, e perde a rusticidade 'caseira'.",
    "chicago_tavern_v2_science_flour": "O objetivo é 'Massa Morta'. Queremos zero elasticidade para que role fina como papel, e zero salto de forno (inchaço). Baixa hidratação + rolo consegue isso.",
    "chicago_tavern_v2_dd_hydration": "45-50%. Extremamente seca. Precisamos prevenir vapor. Vapor cria inchaço. Inchaço cria maciez. Queremos um biscoito morto e plano.",
    "montreal_bagel_science_flour": "Alto glúten necessário para retenção de forma durante a fervura. A falta de sal enfraquece a rede, então uma massa rígida compensa.",
    "montreal_bagel_dd_hydration": "50-55%. Muito rígida.",
    "flour_tortilla_sonora_science_flour": "Alta gordura  água quente  maciez e extensibilidade",
    "flour_tortilla_sonora_dd_hydration": "Pouca água muita gordura",
    "baguette_tradition_science_flour": "Requer farinha T65 com proteína respeitável (11-12%) mas alta extensibilidade. Ao contrário das farinhas americanas de alta proteína, a farinha francesa permite a massa extensível característica que não encolhe ao rolar.",
    "baguette_tradition_science_process": "O \"Décret Pain\" de 1993 proíbe aditivos. A crocância e cor (Maillard) dependem exclusivamente da caramelização natural da farinha e injeção de vapor que gelatiniza o amido superficial, criando uma crosta brilhante, fina e craquelada.",
    "brioche_tete_science_flour": "Requer forte produção de glúten para carregar a carga pesada de gordura. No entanto, T45 é preferida por sua finura.",
    "brioche_tete_science_process": "Uma emulsão estável de gordura e água. A manteiga deve ser adicionada plástica (fria/maleável) apenas DEPOIS do desenvolvimento do glúten. Se adicionada muito cedo, reveste as proteínas e impede a reticulação (efeito gordura).",
    "laugenbrezel_science_flour": "Massa rígida (aprox 50% hidratação) necessária para manter a forma intrincada durante o mergulho e cozimento.",
    "laugenbrezel_science_process": "O mergulho em solução de Hidróxido de Sódio (Lye) (pH 13-14) quebra as proteínas na superfície e promove uma reação de Maillard extrema e acelerada, resultando na cor marrom profunda e sabor específico de \"pretzel\".",
    "english_muffin_science_flour": "Alta proteína é necessária para suportar a alta hidratação (aprox 80%) que cria as grandes bolhas (rincões) durante o cozimento na chapa.",
    "english_muffin_science_process": "O corte com garfo: Cortar com faca corta as fitas de glúten e arruína a textura. Separar com a mão (ou usar um garfo) preserva os picos e vales (rincões) que seguram a manteiga.",
    "khachapuri_adjaruli_science_flour": "Extensibilidade é necessária para dobrar os lados do \"barco\" sem que eles abram de volta durante o cozimento.",
    "khachapuri_adjaruli_science_process": "A forma de barco (Nave) atua como recipiente. A mistura de queijo derrete e emulsiona com a manteiga. A adição final da gema de ovo confia no calor residual do queijo para cozinhar parcialmente (pasteurizar) enquanto se mexe.",
    "danish_rugbrod_science_flour": "O centeio contém glutenina/gliadina mas elas não formam uma rede como o trigo. A estrutura vem dos pentosanos (gomas) e gelatinização do amido. Ácido (Levain) é OBRIGATÓRIO para prevenir o \"ataque de amido\" (amilase destruindo estrutura).",
    "danish_rugbrod_science_process": "O ataque de Amido: O centeio é rico em enzimas amilases. Se o pH não for baixado (<4.5), essas enzimas digerirão o amido durante o cozimento, resultando em um pão gomoso e colapsado. O levain não é apenas para sabor; é uma necessidade estrutural.",
    "tiger_bread_science_flour": "A massa em si é um pão branco vibrante padrão. A ciência está na cobertura.",
    "tiger_bread_science_process": "A pasta Tigre é feita de Farinha de Arroz, Levedura, Açúcar, Óleo e Água. Já que a farinha de arroz não tem glúten, ela não expande. À medida que o pão expande embaixo (Salto de Forno), a pasta de arroz rígida racha, criando o padrão e o crocante intenso.",
    "irish_soda_bread_science_flour": "Farinha de baixa proteína é preferida. Alta proteína o tornaria duro/borrachudo porque não há fermentação para relaxar o glúten.",
    "irish_soda_bread_science_process": "Reação Ácido-Base: Ácido Lático (Buttermilk) + Bicarbonato de Sódio = CO2 + Água + Sal. Essa reação é instantânea. A massa deve ser assada imediatamente ou o gás se perde.",
    "pizza_napoletana_science_flour": "Requer farinha '00' com W280-320. A chave é o controle estrito de P/L (0.50-0.60): precisamos de extensibilidade para estiramento fácil sem encolhimento, mas força suficiente para reter gás durante uma longa fermentação de 24h em temperatura ambiente.",
    "pizza_napoletana_science_process": "O evento físico definidor é a 'Evaporação Súbita'. A >430°C, a umidade na massa vira vapor quase instantaneamente. Como o glúten está relaxado (extensível), o cornicione infla rapidamente antes da crosta firmar, criando os 'vazios' característicos dentro da borda.",
    "pizza_napoletana_dd_hydration": "58-62% é o padrão STG porque o forno a lenha a 485°C requer evaporação rápida sem queimar a crosta. O estilo moderno 'Canotto' usa 70%+, mas exige farinha muito mais forte e habilidades de manuseio avançadas.",
    "pizza_teglia_romana_science_flour": "Requer farinha extremamente forte (W350+, P/L 0.55). A rede de glúten deve ser poderosa o suficiente para segurar 80%+ de água e prender as enormes bolhas de CO2 durante a fermentação a frio.",
    "pizza_teglia_romana_science_process": "A ciência definidora é 'Gelatinização de Amido vs Estrutura de Glúten'. Água alta permite atividade enzimática completa (protease), criando uma textura que derrete na boca. A fermentação a frio (4°C) retarda a levedura mas deixa as bactérias produzirem ácidos que fortalecem o glúten, tornando gerenciável a hidratação impossível.",
    "pizza_teglia_romana_dd_hydration": "80% é o número mágico para a textura de 'nuvem'. Água alta cria bolsas de vapor (alvéolos) e mantém o miolo úmido apesar do cozimento longo. Abaixo de 75%, é apenas focaccia pesada.",
    "pizza_tonda_romana_science_flour": "Força média (W240). Não queremos elasticidade extrema porque a achatamos manualmente. Muito nervo (elasticidade) faz com que encolha.",
    "pizza_tonda_romana_science_process": "A evaporação é o objetivo. Baixa hidratação + Óleo + Rolo = Desidratação. Efetivamente estamos fritando a massa em seu próprio óleo e secando-a para criar uma estrutura de biscoito.",
    "pizza_tonda_romana_dd_hydration": "Baixa hidratação (~56%) é crítica. Queremos restringir a geração de vapor para que a crosta seque e se torne um biscoito. Alta hidratação a tornaria mastigável.",
    "focaccia_genovese_science_flour": "Usa uma farinha de força Média (W260-280). Não queremos elasticidade extrema; a massa deve ser extensível o suficiente para preencher os cantos da forma sem brigar.",
    "focaccia_genovese_science_process": "A Ciência Central é a 'Salamoia' (Emulsão de Salmoura). Despejar uma mistura de água e óleo sobre a massa antes de assar cria uma barreira térmica. O líquido acumula nos furos, impedindo que a massa ali ultrapasse 100°C. Isso essencialmente ferve a massa nos buracos (mantendo-os brancos/macios) enquanto as cristas fritam no óleo (tornando-se douradas/crocantes).",
    "focaccia_genovese_dd_hydration": "65% é equilibrado para uma massa de forma. A chave não é a água dentro, mas o óleo/salmoura fora. A massa ferve nos bolsos de salmoura.",
    "sfincione_palermitano_science_flour": "Semolina Remilled (Rimacinata) misturada com trigo mole. O grão duro fornece uma 'mordida' específica e cor dourada.",
    "sfincione_palermitano_science_process": "Revestimento de gordura. O uso de Banha (Strutto) encurta as fitas de glúten, criando um miolo macio, tipo bolo ('Esponja') em vez de um pão mastigável.",
    "sfincione_palermitano_dd_hydration": "70% hidratação mais 5% Banha cria uma massa 'curta'. A gordura reveste o glúten, prevenindo que se torne duro, resultando em uma textura de bolo esponjoso.",
    "pane_toscano_science_flour": "Usa farinha fraca-média. Sem sal para tensionar a rede de glúten, a massa é quimicamente frouxa e fermenta muito mais rápido.",
    "pane_toscano_science_process": "Cinética de Levedura: O sal é um inibidor de levedura. Removê-lo cria 'Levedura Correndo', significando que a fermentação explode rapidamente. Devemos usar uma Biga ou Levain ácido para controlar essa velocidade e fortalecer o glúten.",
    "pane_toscano_dd_hydration": "60% é padrão. A falta de sal muda a reologia - o sal tensiona o glúten. Sem ele, a massa é naturalmente frouxa, então não precisamos de muita água para a extensibilidade.",
    "ciabatta_classic_science_flour": "Requer Alta Proteína/Alta W (W320+). Com hidratação empurrando 80%, farinha fraca se degradaria em uma sopa devido à atividade de protease. É necessário glúten forte para prender a geração massiva de vapor.",
    "ciabatta_classic_science_process": "A estrutura é impulsionada por 'Bassinage' e 'Expansão de Vapor'. Adicionar água em estágios constrói a rede de glúten primeiro. No forno, o alto teor de água se converte em vapor rapidamente. O glúten forte prende essas bolsas de gás em expansão, criando o 'Miolo Aberto' característico.",
    "ciabatta_classic_dd_hydration": "78-85% é a definição de Ciabatta. Deve ser úmida o suficiente para se nivelar sozinha. A expansão de vapor dessa água cria os buracos massivos."
}

with open(r'c:\Users\eduar\OneDrive\Desktop\Antigravity\doughlabpro\translations_bundle_pt.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
