
import json

data = {
    "new_york_slice_v2_method_direct_notes": "El método clásico de la tienda de porciones, a menudo el mismo día.",
    "new_york_slice_v2_method_biga_notes": "Añade un sabor excelente pero puede hacer la masa demasiado fuerte/reticente para extenderla fácilmente.",
    "new_york_slice_v2_method_poolish_notes": "Común en tiendas de porciones 'Artesanales' modernas para una corteza más ligera e inflada.",
    "detroit_style_classic_method_direct_notes": "Estándar. El molde soporta la estructura, por lo que no se necesita estrictamente un desarrollo de gluten complejo.",
    "detroit_style_classic_method_biga_notes": "Complejidad innecesaria para una pizza de molde.",
    "detroit_style_classic_method_poolish_notes": "Hace la miga más ligera, más tipo focaccia.",
    "chicago_deep_dish_method_direct_notes": "La única forma, mezcla corta uso directo.",
    "chicago_deep_dish_method_biga_notes": "Estilo completamente incorrecto.",
    "chicago_deep_dish_method_poolish_notes": "Estilo completamente incorrecto.",
    "sf_sourdough_method_direct_notes": "Imposible, esto es masa madre.",
    "sf_sourdough_method_biga_notes": "Esto es masa madre.",
    "sf_sourdough_method_poolish_notes": "Esto es masa madre.",
    "new_haven_apizza_method_direct_notes": "Pero necesita fermentación en frío (Retardo) para ser auténtica.",
    "new_haven_apizza_method_biga_notes": "No es típico.",
    "new_haven_apizza_method_poolish_notes": "No es típico.",
    "nyc_bagel_method_direct_notes": "Con masa madre rígida o esponja.",
    "nyc_bagel_method_biga_notes": "Excelente para fijar sabor en una masa rígida.",
    "nyc_bagel_method_poolish_notes": "Comúnmente usado como la fase de 'Esponja'.",
    "grandma_style_v2_method_direct_notes": "La definición del estilo abuela, mezcla elevación corta hornear.",
    "grandma_style_v2_method_biga_notes": "Demasiado elegante.",
    "grandma_style_v2_method_poolish_notes": "Bueno para una versión más ligera.",
    "chicago_tavern_v2_method_direct_notes": "A menudo usado con un enfoque de 'levadura muerta' (curado largo).",
    "chicago_tavern_v2_method_biga_notes": "No queremos volumen.",
    "chicago_tavern_v2_method_poolish_notes": "No queremos hinchazón.",
    "montreal_bagel_method_direct_notes": "Estándar.",
    "flour_tortilla_sonora_method_direct_notes": "Estándar.",
    "baguette_tradition_method_direct_notes": "Posible con 'Pointage Bloc', pero carece de la profundidad de los prefermentos.",
    "baguette_tradition_method_biga_notes": "N/A",
    "baguette_tradition_method_poolish_notes": "La clásica 'Baguette sur Poolish'. Corteza fina, sabor a nuez, masa extensible.",
    "brioche_tete_method_direct_notes": "Estándar. La larga fermentación en frío es necesaria para que la mantequilla se asiente.",
    "brioche_tete_method_biga_notes": "Útil.",
    "brioche_tete_method_poolish_notes": "También útil.",
    "laugenbrezel_method_direct_notes": "Método estándar de masa rígida.",
    "english_muffin_method_direct_notes": "Común pero Poolish es mejor para las burbujas.",
    "english_muffin_method_poolish_notes": "La acidez y actividad enzimática ayudan a crear los 'Rincones y Grietas'.",
    "khachapuri_adjaruli_method_direct_notes": "Estándar.",
    "pizza_napoletana_method_direct_notes": "Ideal y Tradicional. Maximiza el sabor puro del trigo y la digestibilidad con 24h de fermentación.",
    "pizza_napoletana_method_biga_notes": "No tradicional (STG), pero ampliamente usado en 'Neo-Napolitana' para crear volumen extremo en el cornicione y sabor complejo.",
    "pizza_napoletana_method_poolish_notes": "Usado para estilo 'Canotto' (bote) para obtener un borde enorme e inflado, pero la suavidad se desvía de la tradición.",
    "pizza_teglia_romana_method_direct_notes": "El enfoque de fermentación en frío 'Sin Amasado' es efectivamente un método directo simplificado. Muy efectivo.",
    "pizza_teglia_romana_method_biga_notes": "Opción para más sabor.",
    "pizza_teglia_romana_method_poolish_notes": "Excelente para extensibilidad y miga abierta.",
    "pizza_tonda_romana_method_direct_notes": "Estándar, una masa directa simple funciona mejor para esto.",
    "pizza_tonda_romana_method_biga_notes": "Complejidad innecesaria. No queremos el volumen o miga salvaje que proporciona la Biga.",
    "pizza_tonda_romana_method_poolish_notes": "Evitar. Crea demasiada hinchazón.",
    "focaccia_genovese_method_direct_notes": "La forma clásica, levadura alta, tiempo corto, salmuera inmediata.",
    "focaccia_genovese_method_biga_notes": "Añade un buen perfume, pero a menudo considerado 'demasiado elegante' para focaccia de comida callejera.",
    "focaccia_genovese_method_poolish_notes": "Hace una focaccia muy ligera casi tipo pastel.",
    "sfincione_palermitano_method_direct_notes": "Método auténtico, la suavidad viene de la grasa no de prefermentos.",
    "sfincione_palermitano_method_biga_notes": "No es típico para este estilo.",
    "sfincione_palermitano_method_poolish_notes": "No es típico.",
    "pane_toscano_method_direct_notes": "Sin sal para controlar la levadura la masa directa explota.",
    "pane_toscano_method_biga_notes": "Esencial, la acidez de la biga fortalece el gluten.",
    "pane_toscano_method_poolish_notes": "Demasiado débil, necesitamos la fuerza de un prefermento rígido.",
    "ciabatta_classic_method_direct_notes": "No puedes obtener la miga abierta o el sabor sin un prefermento.",
    "ciabatta_classic_method_biga_notes": "El método original de 1982, 100 de harina en la biga.",
    "ciabatta_classic_method_poolish_notes": "Crea una versión de corteza más fina y ligera, pero miga menos 'carnosa'."
}

with open(r'c:\Users\eduar\OneDrive\Desktop\Antigravity\doughlabpro\translations_extended_bundle_es.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
