
import json

data = {
    "new_york_slice_v2_science_flour": "High protein requires oil/sugar (tenderizers) to allow the 'fold' without the crust cracking like a cracker. The gluten density supports the large 18-inch diameter.",
    "new_york_slice_v2_dd_hydration": "62-65% is the sweet spot. It allows the dough to be extensible enough for the 18-inch stretch but provides enough structure to hold the fold ('The Fold') without flopping.",
    "detroit_style_classic_science_flour": "Structure is supported by the steel pan walls, so we don't need extreme gluten strength. High hydration aids the 'focaccia-like' open crumb.",
    "detroit_style_classic_dd_hydration": "70-75% is mandatory. This is effectively a focaccia baked with cheese. The high water ensures the thick crumb remains light and airy like a sponge, not dense like a brick.",
    "chicago_deep_dish_science_flour": "A 'Short Dough'. The high fat content coats the proteins, preventing long gluten chains. This creates a flaky, biscuit-like break instead of a chew.",
    "chicago_deep_dish_dd_hydration": "50-55% plus high fat (15%+ Corn Oil/Butter). This is NOT bread. This is a savory pie crust. High hydration would develop gluten -> chewy -> wrong.",
    "sf_sourdough_science_flour": "Proteolysis (acid degrading gluten) is the enemy. We need very strong flour to survive the long, acidic fermentation without collapsing.",
    "sf_sourdough_dd_hydration": "75%+ is standard. The acidity from the Levain tightens the gluten structure, allowing it to hold significant water without becoming soup. The water is needed for the open crumb.",
    "new_haven_apizza_science_flour": "High strength is required to stretch very thin without tearing, but extended cold fermentation relaxes the gluten (extensibility).",
    "new_haven_apizza_dd_hydration": "60-65% drives the char. It needs to be dry enough to crisp rapidly, but wet enough to undergo the 48h ferment without drying out in the fridge.",
    "nyc_bagel_science_flour": "The highest protein flour possible is used. Because hydration is low (50%), the gluten is incredibly tight, creating the 'jaw workout' chewiness.",
    "nyc_bagel_dd_hydration": "50-55% is stiff. Extremely stiff. This tightness + boiling is what restricts expansion, creating the dense, chewy texture. If you hydrate to 65%, you just made a circle bread roll.",
    "grandma_style_v2_science_flour": "Does not require high protein. A softer flour helps it stretch into the corners of the pan without shrinking back.",
    "grandma_style_v2_dd_hydration": "60-65% ensures a crisp bottom (fried in pan oil) but a dense enough crumb to support toppings. Too airy, and it loses the 'homestyle' rusticity.",
    "chicago_tavern_v2_science_flour": "The goal is 'Dead Dough'. We want zero elasticity so it rolls paper thin, and zero ovenspring (puff). Low hydration + rolling pin achieves this.",
    "chicago_tavern_v2_dd_hydration": "45-50%. Extremely dry. We need to prevent steam. Steam creates puff. Puff creates soft. We want a dead, flat, cracker.",
    "montreal_bagel_science_flour": "High gluten needed for shape retention during boil. Lack of salt weakens network, so stiff dough compensates.",
    "montreal_bagel_dd_hydration": "50-55%. Very stiff.",
    "flour_tortilla_sonora_science_flour": "High fat  hot water  tenderness and extensibility",
    "flour_tortilla_sonora_dd_hydration": "Low water high fat",
    "baguette_tradition_science_flour": "Requires T65 flour with respectable protein (11-12%) but high extensibility. Unlike high-protein American flours, French flour allows for the signature extensible dough that does not shrink back when rolled.",
    "baguette_tradition_science_process": "The \"Décret Pain\" of 1993 prohibits additives. Crispiness and color (Maillard) depend exclusively on natural flour caramelization and steam injection which gelatinizes the surface starch, creating a glossy, thin, crackly crust.",
    "brioche_tete_science_flour": "Requires strong gluten production to carry the heavy load of fat. However, T45 is preferred for its fineness.",
    "brioche_tete_science_process": "A stable emulsion of fat and water. The butter must be added plastic (cold/malleable) only AFTER gluten development. If added too early, it coats the proteins and prevents cross-linking (shortening effect).",
    "laugenbrezel_science_flour": "Stiff dough (approx 50% hydration) required to hold the intricate shape during the dip and bake.",
    "laugenbrezel_science_process": "The dip in Sodium Hydroxide (Lye) solution (pH 13-14) breaks down proteins on the surface and promotes an extreme, accelerated Maillard reaction, resulting in the deep brown color and specific \"pretzel\" flavor.",
    "english_muffin_science_flour": "High protein is needed to support the high hydration (80%ish) which creates the large bubbles (nooks) during the griddle cook.",
    "english_muffin_science_process": "The Fork split: Cutting with a knife shears the gluten strands and ruins the texture. Pulling apart (or using a fork) preserves the peaks and valleys (nooks) that hold the butter.",
    "khachapuri_adjaruli_science_flour": "Extensibility is needed to fold the \"boat\" sides without them snapping back open during baking.",
    "khachapuri_adjaruli_science_process": "The boat shape (Nave) acts as a container. The cheese mixture melts and emulsifies with the butter. The final addition of the egg yolk relies on the residual heat of the cheese to partially cook (pasteurize) it while stirring.",
    "danish_rugbrod_science_flour": "Rye contains glutenin/gliadin but they don't form a network like wheat. Structure comes from Pentosans (gums) and starch gelatinization. Acid (Sourdough) is MANDATORY to prevent \"starch attack\" (amylase destroying structure).",
    "danish_rugbrod_science_process": "The Starch attack: Rye is high in amylase enzymes. If pH is not lowered (<4.5), these enzymes will digest the starch during baking, resulting in a gummy, collapsed loaf. The sourdough is not just for flavor; it is a structural necessity.",
    "tiger_bread_science_flour": "The dough itself is a standard vibrant white bread. The science is in the topping.",
    "tiger_bread_science_process": "The Tiger paste is made of Rice Flour, Yeast, Sugar, Oil, and Water. Since rice flour lacks gluten, it does not expand. As the dough loaf expands underneath (Oven Spring), the rigid rice paste cracks apart, creating the pattern and the intense crunch.",
    "irish_soda_bread_science_flour": "Low protein flour is preferred. High protein would make it tough/rubbery because there is no fermentation to relax the gluten.",
    "irish_soda_bread_science_process": "Acid-Base Reaction: Lactic Acid (Buttermilk) + Sodium Bicarbonate = CO2 + Water + Salt. This reaction is instant. The dough must be baked immediately or the gas is lost.",
    "pizza_napoletana_science_flour": "Requires '00' flour with W280-320. The key is strict P/L control (0.50-0.60): we need extensibility for easy stretching without snap-back, but enough strength to hold gas during a long 24h fermentation at room temperature.",
    "pizza_napoletana_science_process": "The defining physical event is 'Sudden Evaporation'. At >430°C, the moisture in the dough turns to steam almost instantly. Because the gluten is relaxed (extensible), the cornicione inflates rapidly before the crust sets, creating the signature 'voids' inside the rim.",
    "pizza_napoletana_dd_hydration": "58-62% is the STG standard because the 485°C wood-fired oven requires rapid evaporation without burning the crust. The modern 'Canotto' style uses 70%+, but demands much stronger flour and advanced handling skills.",
    "pizza_teglia_romana_science_flour": "Requires extremely strong flour (W350+, P/L 0.55). The gluten network must be powerful enough to hold 80%+ water and trap the massive CO2 bubbles during the cold ferment.",
    "pizza_teglia_romana_science_process": "The defining science is 'Starch Gelatinization vs Gluten Structure'. High water allows full enzymatic activity (protease), creating a melt-in-the-mouth texture. The cold ferment (4°C) slows yeast but lets bacteria produce acids that strengthen the gluten, making the impossible hydration manageable.",
    "pizza_teglia_romana_dd_hydration": "80% is the magic number for the 'cloud' texture. High water creates steam pockets (alveoli) and keeps the crumb moist despite the long bake. Below 75%, it's just heavy focaccia.",
    "pizza_tonda_romana_science_flour": "Medium strength (W240). We don't want extreme elasticity because we manually roll it flat. Too much nerve (elasticity) makes it shrink back.",
    "pizza_tonda_romana_science_process": "Evaporation is the goal. Low hydration + Oil + Rolling Pin = Dehydration. We are effectively frying the dough in its own oil and drying it out to create a biscuit structure.",
    "pizza_tonda_romana_dd_hydration": "Low hydration (~56%) is critical. We want to restrict steam generation so the crust dries out and becomes a cracker. High hydration would make it chewy.",
    "focaccia_genovese_science_flour": "Uses a Medium strength flour (W260-280). We don't want extreme elasticity; the dough must be extensible enough to fill the pan corners without fighting back.",
    "focaccia_genovese_science_process": "The Core Science is the 'Salamoia' (Brine Emulsion). Pouring a mix of water and oil over the dough before baking creates a thermal barrier. The liquid pools in the dimples, preventing the dough there from exceeding 100°C. This essentially boils the dough in the holes (keeping them white/soft) while the ridges fry in oil (becoming golden/crisp).",
    "focaccia_genovese_dd_hydration": "65% is balanced for a pan dough. The key isn't the water inside, but the oil/brine outside. The dough boils in the brine pockets.",
    "sfincione_palermitano_science_flour": "Semolina Remilled (Rimacinata) mixed with soft wheat. The hard grain provides a specific 'bite' and golden color.",
    "sfincione_palermitano_science_process": "Fat coating. The use of Lard (Strutto) shortens the gluten strands, creating a soft, cake-like crumb ('Sponge') rather than a chewy bread.",
    "sfincione_palermitano_dd_hydration": "70% hydration plus 5% Lard creates a 'short' dough. The fat coats the gluten, preventing it from becoming tough, resulting in a sponge cake texture.",
    "pane_toscano_science_flour": "Uses weak-medium flour. Without salt to tighten the gluten network, the dough is chemically slack and ferments much faster.",
    "pane_toscano_science_process": "Yeast Kinetics: Salt is a yeast inhibitor. Removing it creates 'Running Yeast, meaning fermentation explodes rapidly. We must use a Biga or acidic Levain to control this speed and strengthen the gluten.",
    "pane_toscano_dd_hydration": "60% is standard. The lack of salt changes the rheology - salt tightens gluten. Without it, the dough is naturally slack, so we don't need high water for extensibility.",
    "ciabatta_classic_science_flour": "Requires High Protein/High W (W320+). With hydration pushing 80%, weak flour would degrade into a soup due to protease activity. Strong gluten is needed to trap the massive steam generation.",
    "ciabatta_classic_science_process": "Structure is driven by 'Bassinage' and 'Steam Expansion'. Adding water in stages builds the gluten network first. In the oven, the high water content converts to steam rapidly. The strong gluten traps these expanding gas pockets, creating the signature 'Open Crumb'.",
    "ciabatta_classic_dd_hydration": "78-85% is the definition of Ciabatta. It must be wet enough to be self-leveling. The steam expansion from this water creates the massive holes."
}

with open(r'c:\Users\eduar\OneDrive\Desktop\Antigravity\doughlabpro\translations_bundle_en.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
