
import json

data = {
    "new_york_slice_v2_method_direct_notes": "O método clássico da loja de fatias de esquina, muitas vezes no mesmo dia.",
    "new_york_slice_v2_method_biga_notes": "Adiciona sabor excelente, mas pode tornar a massa muito forte/tensa para esticar facilmente.",
    "new_york_slice_v2_method_poolish_notes": "Comum em lojas de fatias 'Artesanais' modernas para uma crosta mais leve e inflada.",
    "detroit_style_classic_method_direct_notes": "Padrão. A forma suporta a estrutura, então o desenvolvimento complexo de glúten não é estritamente necessário.",
    "detroit_style_classic_method_biga_notes": "Complexidade desnecessária para uma pizza de forma.",
    "detroit_style_classic_method_poolish_notes": "Deixa o miolo mais leve, mais tipo focaccia.",
    "chicago_deep_dish_method_direct_notes": "A única maneira, mistura curta uso direto.",
    "chicago_deep_dish_method_biga_notes": "Estilo completamente errado.",
    "chicago_deep_dish_method_poolish_notes": "Estilo completamente errado.",
    "sf_sourdough_method_direct_notes": "Impossível, isso é levain.",
    "sf_sourdough_method_biga_notes": "Isso é levain.",
    "sf_sourdough_method_poolish_notes": "Isso é levain.",
    "new_haven_apizza_method_direct_notes": "Mas precisa de fermentação a frio (Retardo) para ser autêntica.",
    "new_haven_apizza_method_biga_notes": "Não é típico.",
    "new_haven_apizza_method_poolish_notes": "Não é típico.",
    "nyc_bagel_method_direct_notes": "Com levain rígido ou esponja.",
    "nyc_bagel_method_biga_notes": "Excelente para fixar sabor em uma massa rígida.",
    "nyc_bagel_method_poolish_notes": "Comumente usado como a fase de 'Esponja'.",
    "grandma_style_v2_method_direct_notes": "A definição do estilo vovó, mistura elevação curta assar.",
    "grandma_style_v2_method_biga_notes": "Muito chique.",
    "grandma_style_v2_method_poolish_notes": "Bom para uma versão mais leve.",
    "chicago_tavern_v2_method_direct_notes": "Muitas vezes usado com uma abordagem de 'fermento morto' (cura longa).",
    "chicago_tavern_v2_method_biga_notes": "Não queremos volume.",
    "chicago_tavern_v2_method_poolish_notes": "Não queremos inchaço.",
    "montreal_bagel_method_direct_notes": "Padrão.",
    "flour_tortilla_sonora_method_direct_notes": "Padrão.",
    "baguette_tradition_method_direct_notes": "Possível com 'Pointage Bloc', mas carece da profundidade dos pré-fermentos.",
    "baguette_tradition_method_biga_notes": "N/A",
    "baguette_tradition_method_poolish_notes": "A clássica 'Baguette sur Poolish'. Crosta fina, sabor de nozes, massa extensível.",
    "brioche_tete_method_direct_notes": "Padrão. A longa fermentação a frio é necessária para a manteiga firmar.",
    "brioche_tete_method_biga_notes": "Útil.",
    "brioche_tete_method_poolish_notes": "Também útil.",
    "laugenbrezel_method_direct_notes": "Método padrão de massa rígida.",
    "english_muffin_method_direct_notes": "Comum, mas Poolish é melhor para as bolhas.",
    "english_muffin_method_poolish_notes": "A acidez e atividade enzimática ajudam a criar os 'Rincões e Fendas'.",
    "khachapuri_adjaruli_method_direct_notes": "Padrão.",
    "pizza_napoletana_method_direct_notes": "Ideal e Tradicional. Maximiza o sabor puro do trigo e a digestibilidade com 24h de fermentação.",
    "pizza_napoletana_method_biga_notes": "Não tradicional (STG), mas amplamente usado em 'Neo-Napolitana' para criar volume extremo no cornicione e sabor complexo.",
    "pizza_napoletana_method_poolish_notes": "Usado para estilo 'Canotto' (bote) para obter uma borda enorme e inflada, mas a maciez se desvia da tradição.",
    "pizza_teglia_romana_method_direct_notes": "A abordagem de fermentação a frio 'Sem Sovar' é efetivamente um método direto simplificado. Muito eficaz.",
    "pizza_teglia_romana_method_biga_notes": "Opção para mais sabor.",
    "pizza_teglia_romana_method_poolish_notes": "Excelente para extensibilidade e miolo aberto.",
    "pizza_tonda_romana_method_direct_notes": "Padrão, uma massa direta simples funciona melhor para isso.",
    "pizza_tonda_romana_method_biga_notes": "Complexidade desnecessária. Não queremos o volume ou miolo selvagem que a Biga fornece.",
    "pizza_tonda_romana_method_poolish_notes": "Evitar. Cria muito inchaço.",
    "focaccia_genovese_method_direct_notes": "A maneira clássica, fermento alto, tempo curto, salmoura imediata.",
    "focaccia_genovese_method_biga_notes": "Adiciona um bom perfume, mas muitas vezes considerado 'muito chique' para focaccia de comida de rua.",
    "focaccia_genovese_method_poolish_notes": "Cria uma focaccia muito leve quase tipo bolo.",
    "sfincione_palermitano_method_direct_notes": "Método autêntico, a maciez vem da gordura não de pré-fermentos.",
    "sfincione_palermitano_method_biga_notes": "Não é típico para este estilo.",
    "sfincione_palermitano_method_poolish_notes": "Não é típico.",
    "pane_toscano_method_direct_notes": "Sem sal para controlar o fermento a massa direta explode.",
    "pane_toscano_method_biga_notes": "Essencial, a acidez da biga fortalece o glúten.",
    "pane_toscano_method_poolish_notes": "Muito fraco, precisamos da força de um pré-fermento rígido.",
    "ciabatta_classic_method_direct_notes": "Você não consegue o miolo aberto ou o sabor sem um pré-fermento.",
    "ciabatta_classic_method_biga_notes": "O método original de 1982, 100 de farinha na biga.",
    "ciabatta_classic_method_poolish_notes": "Cria uma versão de crosta mais fina e leve, mas miolo menos 'carnudo'."
}

with open(r'c:\Users\eduar\OneDrive\Desktop\Antigravity\doughlabpro\translations_extended_bundle_pt.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=4, ensure_ascii=False)
