import { FlourDefinition } from './types';

export const FLOURS: FlourDefinition[] = [
  // --- CAPUTO (Italy) ---
  {
    id: 'caputo_classica',
    name: 'Caputo Classica (Blue)',
    category: '00',
    strengthW: 220,
    protein: 11.5,
    recommendedUses: ['general', 'focaccia'],
    hydrationHint: { min: 55, max: 65 },
    notes: 'Great all-rounder for direct doughs and short fermentations.',
  },
  {
    id: 'caputo_pizzeria',
    name: 'Caputo Pizzeria (Red)',
    category: '00',
    strengthW: 260,
    protein: 12.5,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 58, max: 68 },
    notes: 'The gold standard for Neapolitan pizza. Ideal for 24h fermentation.',
  },
  {
    id: 'caputo_cuoco',
    name: 'Caputo Cuoco (Chef)',
    category: '00',
    strengthW: 300,
    protein: 13,
    recommendedUses: ['pizza', 'bread'],
    hydrationHint: { min: 62, max: 72 },
    notes: 'Stronger flour for longer fermentations (24h+) and higher hydration.',
  },
  {
    id: 'caputo_nuvola',
    name: 'Caputo Nuvola',
    category: '00',
    strengthW: 270,
    protein: 12.5,
    recommendedUses: ['pizza', 'focaccia'],
    hydrationHint: { min: 65, max: 75 },
    notes: 'Designed for big airy crusts (cornicione). Creates a cloud-like structure.',
  },
  {
    id: 'caputo_nuvola_super',
    name: 'Caputo Nuvola Super',
    category: '00',
    strengthW: 320,
    protein: 13.5,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 70, max: 85 },
    notes: 'High strength version of Nuvola for preferments (biga/poolish) and high hydration.',
  },
  {
    id: 'caputo_manitoba',
    name: 'Caputo Manitoba Oro',
    category: '00',
    strengthW: 370,
    protein: 14,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 70, max: 90 },
    notes: 'Very strong flour enriched with Manitoba wheat. Use for reinforcement or very long ferments (Panettone).',
  },
  {
    id: 'caputo_integrale',
    name: 'Caputo Integrale',
    category: 'whole',
    strengthW: 200,
    protein: 12.5,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 65, max: 75 },
    notes: 'Classic whole wheat flour from Naples.',
  },

  // --- 5 STAGIONI (Italy) ---
  {
    id: '5stagioni_napoletana',
    name: '5 Stagioni Pizza Napoletana (Red)',
    category: '00',
    strengthW: 300,
    protein: 13,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 60, max: 70 },
    notes: 'AVPN approved. Balanced elasticity for traditional Neapolitan pizza.',
  },
  {
    id: '5stagioni_superiore',
    name: '5 Stagioni Superiore (Blue)',
    category: '00',
    strengthW: 330,
    protein: 13.5,
    recommendedUses: ['pizza', 'bread'],
    hydrationHint: { min: 62, max: 75 },
    notes: 'High protein for long maturation times.',
  },

  // --- POLSELLI (Italy) ---
  {
    id: 'polselli_classica',
    name: 'Polselli Classica',
    category: '00',
    strengthW: 270,
    protein: 11.5,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 58, max: 65 },
    notes: 'Traditional pizza flour for direct method.',
  },
  {
    id: 'polselli_super',
    name: 'Polselli Super',
    category: '00',
    strengthW: 320,
    protein: 13,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 65, max: 75 },
    notes: 'Excellent stability for long fermentation.',
  },
  {
    id: 'polselli_vivace',
    name: 'Polselli Vivace',
    category: '00',
    strengthW: 290,
    protein: 12.5,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 60, max: 70 },
    notes: 'Versatile flour for modern pizza requirements.',
  },

  // --- PETRA (Italy - Molino Quaglia) ---
  {
    id: 'petra_1_hp',
    name: 'Petra 1 HP (Stone Ground 1)',
    category: 'other',
    strengthW: 350,
    protein: 14,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 70, max: 85 },
    notes: 'Partially sprouted stone ground flour. Incredible flavor profile.',
  },
  {
    id: 'petra_3_hp',
    name: 'Petra 3 HP (Stone Ground 1/2)',
    category: 'other',
    strengthW: 350,
    protein: 14,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 70, max: 85 },
    notes: 'Focus on pizza. High absorption and stability.',
  },
  {
    id: 'petra_special_pizza',
    name: 'Petra Special Pizza',
    category: '00',
    strengthW: 260,
    protein: 12.5,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 60, max: 70 },
    notes: 'Designed specifically for high-quality pizza making.',
  },

  // --- KING ARTHUR (USA) ---
  {
    id: 'ka_bread',
    name: 'King Arthur Bread Flour',
    category: 'bread',
    strengthW: 360,
    protein: 12.7,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 65, max: 75 },
    notes: 'The American standard for bread flour. Very consistent, malted.',
  },
  {
    id: 'ka_ap',
    name: 'King Arthur All-Purpose',
    category: 'all_purpose',
    strengthW: 280,
    protein: 11.7,
    recommendedUses: ['general', 'pizza', 'bread'],
    hydrationHint: { min: 60, max: 70 },
    notes: 'Stronger than most AP flours, excellent for artisan baking.',
  },
  {
    id: 'ka_sir_lancelot',
    name: 'King Arthur Sir Lancelot',
    category: 'bread',
    strengthW: 400,
    protein: 14.2,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 68, max: 80 },
    notes: 'New York style pizza legend. High gluten for chewy crusts.',
  },
  {
    id: 'ka_whole_wheat',
    name: 'King Arthur Whole Wheat',
    category: 'whole',
    protein: 14,
    recommendedUses: ['bread'],
    hydrationHint: { min: 75, max: 90 },
    notes: 'Made from hard red spring wheat. Strong flavor.',
  },

  // --- CENTRAL MILLING (USA) ---
  {
    id: 'cm_artisan_bakers_craft',
    name: 'Central Milling ABC (Artisan Bakers Craft)',
    category: 'bread',
    protein: 11.5,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 65, max: 75 },
    notes: 'Malted organic white flour. A favorite among artisan bakeries.',
  },
  {
    id: 'cm_high_mountain',
    name: 'Central Milling High Mountain',
    category: 'bread',
    protein: 13.5,
    recommendedUses: ['bread'],
    hydrationHint: { min: 68, max: 80 },
    notes: 'High protein organic flour for structure.',
  },
  {
    id: 'cm_00_normal',
    name: 'Central Milling Reinforced "Type 00"',
    category: '00',
    protein: 11.2,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 60, max: 70 },
    notes: 'American take on the Italian classic. Very extensible.',
  },

  // --- BOB'S RED MILL (USA) ---
  {
    id: 'brm_artisan_bread',
    name: 'Bob\'s Red Mill Artisan Bread Flour',
    category: 'bread',
    protein: 12.5,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 65, max: 75 },
    notes: 'Premium high-protein flour for rustic breads.',
  },
  {
    id: 'brm_ap',
    name: 'Bob\'s Red Mill All-Purpose',
    category: 'all_purpose',
    protein: 11.5,
    recommendedUses: ['general'],
    hydrationHint: { min: 60, max: 70 },
    notes: 'Unbleached and unbromated.',
  },
  {
    id: 'brm_semolina',
    name: 'Bob\'s Red Mill Semolina',
    category: 'other',
    protein: 12,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 55, max: 65 },
    notes: 'Durum wheat semolina, great for dusting or mixing into dough for bite.',
  },

  // --- CAIRNSPRING MILLS (USA) ---
  {
    id: 'cairnspring_trailblazer',
    name: 'Cairnspring Trailblazer',
    category: 'bread',
    protein: 13.5,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 75, max: 90 },
    notes: 'T85 High extraction bread flour. Incredible flavor complexity.',
  },
  {
    id: 'cairnspring_espresso',
    name: 'Cairnspring Espresso',
    category: 'bread',
    protein: 11.5,
    recommendedUses: ['bread'],
    hydrationHint: { min: 70, max: 85 },
    notes: 'Made from Espresso wheat varieties.',
  },

  // --- GENERIC TYPES (Legacy Compatible) ---
  {
    id: 'generic_all_purpose',
    name: 'All-Purpose Flour (Standard)',
    category: 'all_purpose',
    strengthW: 220,
    protein: 10.5,
    recommendedUses: ['pizza', 'bread', 'focaccia', 'general'],
    hydrationHint: {
      min: 58,
      max: 65,
    },
    notes: 'Versatile supermarket flour, good for short fermentations.',
  },
  {
    id: 'generic_rye',
    name: 'Rye Flour (Dark)',
    category: 'other',
    protein: 10,
    recommendedUses: ['bread'],
    hydrationHint: { min: 75, max: 90 },
    notes: 'Low gluten, distinctive flavor. Mix with high gluten flour.',
  },
  {
    id: 'generic_spelt',
    name: 'Spelt Flour',
    category: 'other',
    protein: 13,
    recommendedUses: ['bread'],
    hydrationHint: { min: 65, max: 75 },
    notes: 'Ancient grain, nutty flavor, very extensible gluten.',
  },
  {
    id: 'generic_durum',
    name: 'Durum / Semola Rimacinata',
    category: 'other',
    protein: 12,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 60, max: 70 },
    notes: 'Yellow flour from durum wheat. Adds crunch and golden color.',
  },
  {
    id: 'whole_wheat',
    name: 'Whole Wheat Flour',
    category: 'whole',
    protein: 13,
    recommendedUses: ['bread'],
    hydrationHint: {
      min: 70,
      max: 85,
    },
    notes: 'Absorbs more water. Usually mixed 20-50% with white flour under "Other".',
  },
];
