import { FlourDefinition } from './types';


export const FLOURS: FlourDefinition[] = [
  // --- TYPE 00 (ITALIAN STYLE) ---
  {
    id: 'caputo_classica', // Keeping ID for backward compatibility
    name: 'Type 00 - Classic (W220)',
    category: '00',
    strengthW: 220,
    protein: 11.5,
    recommendedUses: ['general', 'focaccia'],
    hydrationHint: { min: 55, max: 65 },
    notes: 'Standard soft wheat flour. Great for direct doughs and short fermentations.',
  },
  {
    id: 'caputo_pizzeria',
    name: 'Type 00 - Medium Strength (W260)',
    category: '00',
    strengthW: 260,
    protein: 12.5,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 58, max: 68 },
    notes: 'The standard for Neapolitan pizza. Ideal for 24h fermentation.',
  },
  {
    id: 'caputo_cuoco',
    name: 'Type 00 - Strong (W300)',
    category: '00',
    strengthW: 300,
    protein: 13,
    recommendedUses: ['pizza', 'bread'],
    hydrationHint: { min: 62, max: 72 },
    notes: 'Stronger flour for longer fermentations (24h-48h) and higher hydration.',
  },
  {
    id: 'caputo_nuvola_super',
    name: 'Type 00 - Very Strong (W320)',
    category: '00',
    strengthW: 320,
    protein: 13.5,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 70, max: 85 },
    notes: 'High strength for preferments (biga/poolish) and high hydration.',
  },
  {
    id: 'caputo_manitoba',
    name: 'Type 00 - Manitoba (W370)',
    category: '00',
    strengthW: 370,
    protein: 14,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 70, max: 90 },
    notes: 'Type 0/00 reinforced with Manitoba. Ultra strong for very long ferments or Panettone.',
  },

  // --- BREAD FLOUR ---
  {
    id: 'ka_bread',
    name: 'Bread Flour - Standard (12.7%)',
    category: 'bread',
    strengthW: 360,
    protein: 12.7,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 65, max: 75 },
    notes: 'Standard hard red wheat bread flour. Good elasticity.',
  },
  {
    id: 'ka_sir_lancelot',
    name: 'Bread Flour - High Gluten (14.2%)',
    category: 'bread',
    strengthW: 400,
    protein: 14.2,
    recommendedUses: ['pizza'],
    hydrationHint: { min: 68, max: 80 },
    notes: 'High protein "New York Style" flour. Very chewy crusts.',
  },
  {
    id: 'cairnspring_trailblazer',
    name: 'Bread Flour - High Extraction (T85)',
    category: 'bread',
    protein: 13.5,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 75, max: 90 },
    notes: 'Stone-milled or high extraction. More flavor, absorbs more water.',
  },

  // --- ALL PURPOSE ---
  {
    id: 'generic_all_purpose',
    name: 'All-Purpose - Standard (10.5%)',
    category: 'all_purpose',
    strengthW: 220,
    protein: 10.5,
    recommendedUses: ['pizza', 'bread', 'focaccia', 'general'],
    hydrationHint: { min: 58, max: 65 },
    notes: 'Versatile supermarket flour. Best for cookies, cakes, or quick breads.',
  },
  {
    id: 'ka_ap',
    name: 'All-Purpose - Strong (11.7%)',
    category: 'all_purpose',
    strengthW: 280,
    protein: 11.7,
    recommendedUses: ['general', 'pizza', 'bread'],
    hydrationHint: { min: 60, max: 70 },
    notes: 'Premium all-purpose with higher protein. Good for artisan baking.',
  },

  // --- WHOLE & SPECIALTY ---
  {
    id: 'whole_wheat',
    name: 'Whole Wheat Flour',
    category: 'whole',
    protein: 13,
    recommendedUses: ['bread'],
    hydrationHint: { min: 70, max: 85 },
    notes: '100% extraction. Thirsty flour, usually mixed with white flour.',
  },
  {
    id: 'generic_rye',
    name: 'Rye Flour',
    category: 'other',
    protein: 10,
    recommendedUses: ['bread'],
    hydrationHint: { min: 75, max: 90 },
    notes: 'Low gluten, distinctive flavor. Sticky dough.',
  },
  {
    id: 'generic_spelt',
    name: 'Spelt Flour',
    category: 'other',
    protein: 13,
    recommendedUses: ['bread'],
    hydrationHint: { min: 65, max: 75 },
    notes: 'Ancient grain, nutty flavor, very extensible.',
  },
  {
    id: 'generic_durum',
    name: 'Semola Rimacinata (Durum)',
    category: 'other',
    protein: 12,
    recommendedUses: ['bread', 'pizza'],
    hydrationHint: { min: 60, max: 70 },
    notes: 'Yellow durum wheat. Adds crunch and golden color.',
  },
];
