

import { PizzaRecipe } from './types';
import i18n from '@/i18n';

const t = i18n.t.bind(i18n);

export const PIZZA_RECIPES: PizzaRecipe[] = [
  // --- Italian Classics ---
  {
    id: 'margherita',
    name: 'Margherita',
    image: 'https://source.unsplash.com/random/400x300/?margherita,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 250, hydration: 60, styleId: 'neapolitan_avpn_classic' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: [t('ui.fior_di_latte'), t('ui.fresh_basil'), t('ui.extra_virgin_olive_oil')], grams: 100 },
    techniqueNotes: 'Basil and oil added post-oven to preserve aroma.',
  },
  {
    id: 'marinara',
    name: 'Marinara',
    image: 'https://source.unsplash.com/random/400x300/?marinara,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 250, hydration: 60, styleId: 'neapolitan_avpn_classic' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: [t('ui.sliced_garlic'), t('ui.oregano'), t('ui.extra_virgin_olive_oil_2')], grams: 20 },
    techniqueNotes: 'A cheese-less pizza highlighting sauce and garlic quality.',
  },
  {
    id: 'quattro_formaggi',
    name: 'Quattro Formaggi (4 Cheeses)',
    image: 'https://source.unsplash.com/random/400x300/?cheese,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 280, hydration: 65, styleId: 'roman_pala' },
    oven: { tempC: 320 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: [t('ui.mozzarella'), t('ui.gorgonzola'), t('ui.provolone'), t('ui.parmesan')], grams: 180 },
    techniqueNotes: 'White base (bianca), focused on cheese complexity.',
  },
  {
    id: 'prosciutto_e_rucola',
    name: 'Prosciutto e Rucola',
    image: 'https://source.unsplash.com/random/400x300/?prosciutto,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 260, hydration: 62, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 70 },
    toppings: { main: [t('ui.mozzarella_2'), t('ui.prosciutto_crudo'), t('ui.arugula'), t('ui.parmesan_shavings')], grams: 140 },
    techniqueNotes: 'Prosciutto, arugula, and parmesan added post-oven.',
  },
  {
    id: 'diavola',
    name: 'Diavola',
    image: 'https://source.unsplash.com/random/400x300/?salami,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 260, hydration: 62, styleId: 'pizza_napoletana_avpn' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: [t('ui.mozzarella_3'),], grams: 150 },
  },
  {
    id: 'capricciosa',
    name: 'Capricciosa',
    image: 'https://source.unsplash.com/random/400x300/?capricciosa,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 280, hydration: 64, styleId: 'roman_pala' },
    oven: { tempC: 350 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: [t('ui.mozzarella_4'), t('ui.cooked_ham'), t('ui.mushrooms'), t('ui.artichokes'), t('ui.olives')], grams: 180 },
    techniqueNotes: 'A rich and varied pizza.',
  },

  // --- American Classics ---
  {
    id: 'ny_pepperoni',
    name: 'NY Style Pepperoni',
    image: 'https://source.unsplash.com/random/400x300/?pepperoni,pizza',
    origin: 'American',
    dough: { ballWeightG: 350, hydration: 63, styleId: 'new_york_style_pizza' },
    oven: { tempC: 290 },
    sauce: { type: 'Tomato', grams: 120 },
    toppings: { main: [t('ui.lowmoisture_mozzarella'), t('ui.pepperoni')], grams: 250 },
    techniqueNotes: 'Cooked seasoned sauce, sliced or coarse grated cheese.',
  },
  {
    id: 'detroit_style',
    name: 'Detroit Style',
    image: 'https://source.unsplash.com/random/400x300/?detroit,pizza',
    origin: 'American',
    dough: { ballWeightG: 400, hydration: 72, styleId: 'detroit_style' },
    oven: { tempC: 260 },
    sauce: { type: 'Tomato', grams: 150 },
    toppings: { main: [t('ui.wisconsin_brick_cheese'), t('ui.pepperoni_2')], grams: 300 },
    techniqueNotes: 'Baked in steel pan. Cheese to edges, sauce applied in stripes on top.',
  },
  {
    id: 'chicago_deep_dish',
    name: 'Chicago Deep Dish',
    image: 'https://source.unsplash.com/random/400x300/?chicago,pizza',
    origin: 'American',
    dough: { ballWeightG: 500, hydration: 58, styleId: 'chicago_tavern_style' },
    oven: { tempC: 220 },
    sauce: { type: 'Tomato', grams: 200 },
    toppings: { main: [t('ui.italian_sausage'), t('ui.parmesan_2')], grams: 400 },
    techniqueNotes: 'Inverted assembly: dough, cheese, filling, sauce on top. Long bake time.',
  },
  {
    id: 'hawaiian',
    name: 'Hawaiian',
    image: 'https://source.unsplash.com/random/400x300/?hawaiian,pizza',
    origin: 'American',
    dough: { ballWeightG: 300, hydration: 62, styleId: 'new_york_style_pizza' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: [t('ui.mozzarella_5'), t('ui.cooked_ham_2'), t('ui.pineapple')], grams: 220 },
    techniqueNotes: 'Pineapple must be well drained to avoid excess moisture.',
  },
  {
    id: 'bbq_chicken',
    name: 'BBQ Chicken',
    image: 'https://source.unsplash.com/random/400x300/?bbq,pizza',
    origin: 'American',
    dough: { ballWeightG: 320, hydration: 65, styleId: 'new_york_style_pizza' },
    oven: { tempC: 270 },
    sauce: { type: 'Other', grams: 100 }, // BBQ Sauce
    toppings: { main: [t('ui.mozzarella_6'), t('ui.shredded_chicken'), t('ui.red_onion'), t('ui.cilantro')], grams: 240 },
    techniqueNotes: 'BBQ sauce base instead of tomato.',
  },

  // --- Brazilian Classics ---
  {
    id: 'calabresa',
    name: 'Calabresa',
    image: 'https://source.unsplash.com/random/400x300/?calabresa,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: [t('ui.calabresa_sausage'), t('ui.sliced_onion'), t('ui.black_olives')], grams: 200 },
    techniqueNotes: 'Variations exist with or without mozzarella under calabresa.',
  },
  {
    id: 'portuguesa',
    name: 'Portuguesa',
    image: 'https://source.unsplash.com/random/400x300/?portuguesa,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: [t('ui.mozzarella_7'), t('ui.cooked_ham_3'), t('ui.boiled_egg'), t('ui.onion'), t('ui.peas'), t('ui.olives_2')], grams: 280 },
    techniqueNotes: 'Heavy topping load requires sturdy dough.',
  },
  {
    id: 'frango_catupiry',
    name: 'Chicken with Catupiry',
    image: 'https://source.unsplash.com/random/400x300/?chicken,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: [t('ui.mozzarella_8'), t('ui.shredded_chicken_2'), t('ui.catupiry_cheese')], grams: 250 },
    techniqueNotes: 'Catupiry applied in drops or spirals over chicken.',
  },
  {
    id: 'quatro_queijos_br',
    name: 'Four Cheeses (Brazil)',
    image: 'https://source.unsplash.com/random/400x300/?fourcheese,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: [t('ui.mozzarella_9'), t('ui.provolone_2'), t('ui.gorgonzola_2'), t('ui.parmesan_3')], grams: 220 },
    techniqueNotes: 'Often includes Catupiry as optional fifth cheese.',
  },
  {
    id: 'carne_seca_catupiry',
    name: 'Dried Meat with Catupiry',
    image: 'https://source.unsplash.com/random/400x300/?carneseca,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: [t('ui.catupiry_cheese_2'), t('ui.desalted_shredded_dried_meat'), t('ui.red_onion_2')], grams: 260 },
    techniqueNotes: 'White base with Catupiry instead of tomato sauce.',
  },
  {
    id: 'palmito',
    name: 'Heart of Palm',
    image: 'https://source.unsplash.com/random/400x300/?palmito,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: [t('ui.mozzarella_10'), t('ui.sliced_heart_of_palm')], grams: 230 },
    techniqueNotes: 'Heart of palm must be well drained.',
  },
  {
    id: 'vegetariana',
    name: 'Vegetarian',
    image: 'https://source.unsplash.com/random/400x300/?vegetarian,pizza',
    origin: 'International',
    dough: { ballWeightG: 280, hydration: 65, styleId: 'massa_direta_universal' },
    oven: { tempC: 290 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: [t('ui.mozzarella_11'), t('ui.bell_pepper'), t('ui.onion_2'), t('ui.mushrooms_2'), t('ui.olives_3')], grams: 200 },
    techniqueNotes: 'Pre-cook mushrooms and peppers to reduce moisture.',
  },
  {
    id: 'bianca_alho',
    name: 'Pizza Bianca with Garlic',
    image: 'https://source.unsplash.com/random/400x300/?garlic,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 260, hydration: 68, styleId: 'roman_pala' },
    oven: { tempC: 320 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: [t('ui.mozzarella_12'), t('ui.thin_sliced_garlic'), t('ui.olive_oil'), t('ui.rosemary')], grams: 130 },
    techniqueNotes: 'Drizzle with oil before baking to infuse garlic flavor.',
  },
  {
    id: 'fugazza',
    name: 'Fugazza with Cheese',
    image: 'https://source.unsplash.com/random/400x300/?onion,pizza',
    origin: 'Argentinian',
    dough: { ballWeightG: 450, hydration: 65, styleId: 'pizza_teglia_pan_alta' },
    oven: { tempC: 250 },
    sauce: { type: 'None', grams: 0 },
    toppings: { main: [t('ui.mozzarella_13'), t('ui.abundant_onion'), t('ui.oregano_2')], grams: 350 },
    techniqueNotes: 'High soft dough, generous onion and cheese layer on top.',
  },
  {
    id: 'pesto_frango',
    name: 'Chicken Pesto',
    image: 'https://source.unsplash.com/random/400x300/?pesto,pizza',
    origin: 'Modern',
    dough: { ballWeightG: 300, hydration: 65, styleId: 'massa_direta_universal' },
    oven: { tempC: 280 },
    sauce: { type: 'Pesto', grams: 80 },
    toppings: { main: [t('ui.mozzarella_14'), t('ui.grilled_chicken'), t('ui.cherry_tomatoes')], grams: 220 },
    techniqueNotes: 'Pesto replaces tomato sauce creating aromatic base.',
  },
  {
    id: 'marguerita_bufala',
    name: 'Buffalo Margherita',
    image: 'https://source.unsplash.com/random/400x300/?bufala,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 250, hydration: 60, styleId: 'neapolitan_avpn_classic' },
    oven: { tempC: 450 },
    sauce: { type: 'Tomato', grams: 80 },
    toppings: { main: [t('ui.buffalo_mozzarella'), t('ui.fresh_basil_2')], grams: 120 },
    techniqueNotes: 'Buffalo mozzarella releases more water; use in very hot oven.',
  },
  {
    id: 'funghi',
    name: 'Funghi (Mushroom)',
    image: 'https://source.unsplash.com/random/400x300/?mushroom,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 270, hydration: 65, styleId: 'roman_pala' },
    oven: { tempC: 320 },
    sauce: { type: 'White', grams: 60 },
    toppings: { main: [t('ui.mozzarella_15'), t('ui.sautéed_mushroom_mix'), t('ui.parsley')], grams: 180 },
    techniqueNotes: 'Sautéing mushrooms before is essential to remove water.',
  },
  {
    id: 'bacon_milho',
    name: 'Bacon & Corn',
    image: 'https://source.unsplash.com/random/400x300/?bacon,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 100 },
    toppings: { main: [t('ui.mozzarella_16'), t('ui.bacon_cubes'), t('ui.corn')], grams: 240 },
    techniqueNotes: 'Pre-frying bacon helps make it crispier.',
  },
  {
    id: 'tonno_cipolla',
    name: 'Tonno e Cipolla (Tuna & Onion)',
    image: 'https://source.unsplash.com/random/400x300/?tuna,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 260, hydration: 62, styleId: 'massa_direta_universal' },
    oven: { tempC: 300 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: [t('ui.mozzarella_17'), t('ui.canned_tuna'), t('ui.red_onion_3')], grams: 190 },
    techniqueNotes: 'Drain tuna well to avoid excess oil.',
  },
  {
    id: 'supreme',
    name: 'Supreme Pizza',
    image: 'https://source.unsplash.com/random/400x300/?supreme,pizza',
    origin: 'American',
    dough: { ballWeightG: 380, hydration: 63, styleId: 'new_york_style_pizza' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 120 },
    toppings: { main: [t('ui.mozzarella_18'), t('ui.pepperoni_3'), t('ui.sausage'), t('ui.bell_pepper_2'), t('ui.onion_3'), t('ui.olives_4')], grams: 300 },
    techniqueNotes: 'Loaded pizza requiring sturdy dough.',
  },
  {
    id: 'siciliana',
    name: 'Sicilian',
    image: 'https://source.unsplash.com/random/400x300/?sicilian,pizza',
    origin: 'Italian',
    dough: { ballWeightG: 500, hydration: 68, styleId: 'sicilian_sfincione' },
    oven: { tempC: 240 },
    sauce: { type: 'Tomato', grams: 150 },
    toppings: { main: [t('ui.mozzarella_19'), t('ui.anchovies'), t('ui.oregano_3')], grams: 250 },
    techniqueNotes: 'High fluffy dough, baked in rectangular pan greased with olive oil.',
  },
  {
    id: 'mortadela_pistache',
    name: 'Mortadella & Pistachio',
    image: 'https://source.unsplash.com/random/400x300/?mortadella,pizza',
    origin: 'Modern',
    dough: { ballWeightG: 280, hydration: 70, styleId: 'roman_pala' },
    oven: { tempC: 300 },
    sauce: { type: 'White', grams: 70 },
    toppings: { main: [t('ui.fior_di_latte_2'), t('ui.italian_mortadella'), t('ui.crushed_pistachios'), t('ui.lemon_zest')], grams: 180 },
    techniqueNotes: 'Mortadella, pistachios, and zest added post-oven.',
  },
  {
    id: 'escarola',
    name: 'Escarole',
    image: 'https://source.unsplash.com/random/400x300/?escarole,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: [t('ui.mozzarella_20'), t('ui.sautéed_escarole'), t('ui.bacon'), t('ui.olives_5')], grams: 260 },
    techniqueNotes: 'Escarole must be well sautéed and drained to remove moisture and bitterness.',
  },
  {
    id: 'lombo_catupiry',
    name: 'Pork Loin with Catupiry',
    image: 'https://source.unsplash.com/random/400x300/?porkloin,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'Tomato', grams: 90 },
    toppings: { main: [t('ui.mozzarella_21'), t('ui.canadian_pork_loin'), t('ui.catupiry_cheese_3'), t('ui.onion_4')], grams: 270 },
    techniqueNotes: 'Popular combo balancing salty loin with creamy cheese.',
  },
  {
    id: 'peito_peru_br',
    name: 'Turkey Breast',
    image: 'https://source.unsplash.com/random/400x300/?turkey,pizza',
    origin: 'Brazilian',
    dough: { ballWeightG: 320, hydration: 60, styleId: 'pizza_classica_brasileira' },
    oven: { tempC: 280 },
    sauce: { type: 'White', grams: 80 },
    toppings: { main: [t('ui.minas_cheese'), t('ui.smoked_turkey_breast'), t('ui.leeks')], grams: 250 },
    techniqueNotes: 'Lighter version, often found with white cheese base.',
  },
];
